import{auth,db,signInAnonymously,onAuthStateChanged,ref,set,get,update,remove,onValue,onDisconnect,runTransaction}from"./firebase.js";
import{LEVELS}from"./levels.js";import{QUESTIONS}from"./questions.js";import{CFG,newPlayer,newGame,roll,nextTurn,question,move,quizResult,useBoost}from"./game.js";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const AV=["🐼","🐼","🐼","🐼"],COL=["Mint","Berry","Sun","Night"];
const S={lang:"bn",theme:"day",sound:true,mode:null,capacity:4,level:1,difficulty:"medium",game:null,user:null,roomCode:null,room:null,unsub:null,q:null,qAnswered:false,timer:null};
const screens=["#home","#setup","#online","#lobby","#game","#result"];
function go(id){screens.forEach(x=>$(x).classList.remove("active"));$(id).classList.add("active")}
function toast(m){const t=$("#toast");t.textContent=m;t.classList.remove("hidden");setTimeout(()=>t.classList.add("hidden"),1800)}
function name(v,f){v=(v||"").trim().replace(/[<>]/g,"").slice(0,18);return v||f}
function levelName(n){return S.lang==="bn"?LEVELS[n].bn:LEVELS[n].en}
function roomCode(){return String(Math.floor(100000+Math.random()*900000))}
function currentId(){if(S.mode==="online")return S.user?.uid;return S.game?.currentTurn}
function canAct(){if(!S.game||S.game.status!=="playing")return false;if(S.mode==="online")return S.game.currentTurn===S.user?.uid;if(S.mode==="solo")return S.game.currentTurn==="p1";return true}
function renderLevels(){const b=$("#levelPicker");b.innerHTML="";Object.keys(LEVELS).forEach(n=>{const x=document.createElement("button");x.className="level-btn"+(+n===S.level?" selected":"");x.innerHTML=`<b>Level ${n}</b><small>${levelName(n)}</small>`;x.onclick=()=>{S.level=+n;renderLevels()};b.appendChild(x)})}
function renderLobbyLevel(){const s=$("#lobbyLevel");s.innerHTML="";Object.keys(LEVELS).forEach(n=>{const o=document.createElement("option");o.value=n;o.textContent=`${n} — ${levelName(n)}`;s.appendChild(o)});s.value=S.room?.settings?.level||1;$("#lobbyDifficulty").value=S.room?.settings?.difficulty||"medium"}
function renderNames(){const w=$("#nameInputs");w.innerHTML="";const count=S.mode==="solo"?1:S.capacity;for(let i=0;i<count;i++){const d=document.createElement("div");d.className="player-field";d.innerHTML=`<span>Player ${i+1}</span><input id="pname${i}" maxlength="18" value="Player ${i+1}"><div class="avatar-row">${AV.map((a,j)=>`<button class="avatar-chip ${j===i%4?"selected":""}" data-p="${i}" data-a="${j}">${a}</button>`).join("")}</div>`;w.appendChild(d)}$$(".avatar-chip").forEach(b=>b.onclick=()=>{$$(`.avatar-chip[data-p="${b.dataset.p}"]`).forEach(x=>x.classList.remove("selected"));b.classList.add("selected")})}
function applyLang(){$("#langBtn").textContent=S.lang==="bn"?"EN":"বাংলা";$("#heroTitle").textContent=S.lang==="bn"?"পান্ডাদের সাথে খেলতে খেলতে নিউট্রিশন শিখুন":"Learn nutrition while competing with the Panda crew";$("#heroText").textContent=S.lang==="bn"?"১–৪ জন, Online Room, Local Multiplayer, Solo AI, ৫ Level, ৩ Difficulty, Quiz Battle, Power-ups এবং 3D-style board animation.":"1–4 players, online rooms, local multiplayer, solo AI, 5 levels, 3 difficulties, quiz battles, power-ups and 3D-style board animation.";$("#soloSub").textContent=S.lang==="bn"?"কম্পিউটারের বিরুদ্ধে":"Against the computer";$("#localSub").textContent=S.lang==="bn"?"এক ডিভাইসে বন্ধুদের সাথে":"Friends on one device";$("#onlineSub").textContent=S.lang==="bn"?"Room code দিয়ে লাইভ":"Live with a room code";$("#yourNameLabel").textContent=S.lang==="bn"?"আপনার নাম":"Your name";renderLevels();if(S.game)renderGame()}
function setTheme(){document.documentElement.dataset.theme=S.theme;$("#themeBtn").textContent=S.theme==="day"?"🌙":"☀️"}
function modeSetup(m){S.mode=m;if(m==="online"){go("#online");return}if(m==="challenge"){S.mode="solo";S.capacity=2;S.level=((new Date().getDate()-1)%5)+1;S.difficulty="hard";renderNames();go("#setup");toast("🎯 Daily Challenge");return}S.capacity=m==="solo"?2:4;$("#capacityWrap").style.display=m==="solo"?"none":"block";renderNames();go("#setup")}
function startLocal(){const ps=[];if(S.mode==="solo"){ps.push(newPlayer("p1",name($("#pname0").value,"Player 1"),"🐼",1));ps.push(newPlayer("p2","NutriBot 🦊","🦊",2,true))}else{for(let i=0;i<S.capacity;i++){const av=$(`.avatar-chip[data-p="${i}"].selected`)?.dataset.a||i%4;ps.push(newPlayer(`p${i+1}`,name($(`#pname${i}`).value,`Player ${i+1}`),AV[av],i+1))}}S.game=newGame({mode:S.mode,level:S.level,difficulty:S.difficulty,players:ps});go("#game");renderBoard();renderGame()}
function renderBoard(){const b=$("#board");b.innerHTML="";const L=LEVELS[S.game.level],cells=[];for(let r=9;r>=0;r--){let a=[...Array(10)].map((_,i)=>r*10+i+1);if(r%2)a.reverse();cells.push(...a)}cells.forEach(n=>{let ic="";if(L.ladders[n])ic="🪜";else if(L.snakes[n])ic="🐍";else if(L.quiz.includes(n))ic="❓";else if(L.bonus.includes(n))ic="⚡";else if(L.trap.includes(n))ic="🍭";else if(L.duel.includes(n))ic="⚔️";const c=document.createElement("div");c.className="cell";c.dataset.pos=n;c.innerHTML=`<span class="cell-num">${n}</span><span class="cell-icon">${ic}</span><div class="tokens"></div>`;b.appendChild(c)})}
function renderTokens(){$$(".tokens").forEach(x=>x.innerHTML="");if(!S.game)return;S.game.playerOrder.forEach((id,i)=>{const p=S.game.players[id],c=$(`.cell[data-pos="${Math.max(1,p.position)}"] .tokens`);if(c){const t=document.createElement("span");t.className=`token t${i+1}`;t.textContent=p.avatar||"🐼";t.title=p.name;c.appendChild(t)}})}
function renderPlayers(){const w=$("#playerCards");w.innerHTML="";S.game.playerOrder.forEach((id,i)=>{const p=S.game.players[id];const d=document.createElement("div");d.className="player-card"+(id===S.game.currentTurn?" active":"");d.innerHTML=`<div class="player-top"><b>${p.avatar||"🐼"} ${p.name}</b><b>${p.position}/100</b></div><div class="player-meta"><span>Score ${p.score}</span><span>🔥 ${p.streak}</span></div>`;w.appendChild(d)})}
function renderPower(){const p=S.game?.players?.[currentId()],w=$("#powerups");w.innerHTML="";if(!p)return;[["shield","🛡️ Shield"],["hint","💡 Hint"],["boost","⚡ Boost"],["freeze","❄️ Freeze"]].forEach(([k,l])=>{const b=document.createElement("button");b.className="power-btn";b.innerHTML=`<span>${l}</span><b>${p.powerups?.[k]||0}</b>`;b.disabled=k!=="boost"||!p.powerups?.boost||!canAct();if(k==="boost")b.onclick=boostUI;w.appendChild(b)})}
function diceAnim(v){const m={1:"rotateX(0deg) rotateY(0deg)",2:"rotateY(-90deg)",3:"rotateX(-90deg)",4:"rotateX(90deg)",5:"rotateY(90deg)",6:"rotateY(180deg)"};$("#diceCube").style.transform=(m[v]||"")+" rotateZ(360deg)"}
function renderGame(){if(!S.game)return;$("#levelBadge").textContent=`Level ${S.game.level} • ${S.game.difficulty.toUpperCase()}`;$("#levelTitle").textContent=levelName(S.game.level);const p=S.game.players[S.game.currentTurn];$("#turnName").textContent=p?.name||"";$("#phaseText").textContent=S.game.phase==="quiz"?"Quiz":(canAct()?"Your turn":"Waiting…");$("#eventLog").textContent=S.game.lastEvent||"";$("#streakBadge").textContent=`🔥 ${p?.streak||0}`;$("#rollBtn").disabled=!canAct()||S.game.phase!=="roll";renderPlayers();renderTokens();renderPower();if(S.game.dice)diceAnim(S.game.dice);if(S.game.status==="finished")showResult()}
function localRoll(){if(!canAct())return;const d=roll();S.game.dice=d;diceAnim(d);const ev=move(S.game,S.game.currentTurn,d);renderGame();if(ev.t==="quiz"){const q=question(S.game.level,S.game.difficulty,S.game.usedQuestions);S.game.pendingQuestionId=q.id;S.game.usedQuestions.push(q.id);openQuiz(q)}else{nextTurn(S.game);renderGame();if(S.mode==="solo"&&S.game.currentTurn==="p2")setTimeout(aiTurn,700)}}
function aiTurn(){if(!S.game||S.game.currentTurn!=="p2")return;const d=roll();S.game.dice=d;diceAnim(d);const ev=move(S.game,"p2",d);renderGame();if(ev.t==="quiz"){const q=question(S.game.level,S.game.difficulty,S.game.usedQuestions);const ok=Math.random()<CFG[S.game.difficulty].ai;setTimeout(()=>{quizResult(S.game,"p2",ok);nextTurn(S.game);renderGame()},650)}else{nextTurn(S.game);renderGame()}}
function qById(id){return QUESTIONS.find(q=>q.id===id)}
function openQuiz(q){S.q=q;S.qAnswered=false;$("#quizModal").classList.remove("hidden");$("#quizContinue").classList.add("hidden");$("#quizFeedback").textContent="";$("#quizCategory").textContent=q.category;const L=q[S.lang];$("#quizQuestion").textContent=L.q;const w=$("#quizOptions");w.innerHTML="";L.options.forEach((o,i)=>{const b=document.createElement("button");b.className="quiz-option";b.textContent=o;b.onclick=()=>answerQuiz(i);w.appendChild(b)});clearInterval(S.timer);let sec=CFG[S.game.difficulty].timer;$("#quizTimer").textContent=sec||"∞";if(sec)S.timer=setInterval(()=>{sec--;$("#quizTimer").textContent=sec;if(sec<=0){clearInterval(S.timer);answerQuiz(-1)}},1000)}
function answerQuiz(i){if(S.qAnswered)return;S.qAnswered=true;clearInterval(S.timer);const ok=i===S.q.answer,L=S.q[S.lang];$$(".quiz-option").forEach((b,j)=>{b.disabled=true;if(j===S.q.answer)b.classList.add("correct");else if(j===i)b.classList.add("wrong")});$("#quizFeedback").textContent=`${ok?"✅ Correct!":"❌ Wrong."} ${L.explanation}`;$("#quizContinue").dataset.ok=ok?"1":"0";$("#quizContinue").classList.remove("hidden")}
function continueQuiz(){const ok=$("#quizContinue").dataset.ok==="1";$("#quizModal").classList.add("hidden");if(S.mode==="online"){onlineAnswer(ok);return}quizResult(S.game,S.game.currentTurn,ok);nextTurn(S.game);renderGame();if(S.mode==="solo"&&S.game.currentTurn==="p2")setTimeout(aiTurn,700)}
function boostUI(){if(S.mode==="online"){onlineBoost();return}if(useBoost(S.game,S.game.currentTurn)){renderGame();toast("⚡ +3")}}
function showResult(){go("#result");const w=S.game.players[S.game.winner];$("#resultTitle").textContent=`🏆 ${w?.name||"Winner"}`;$("#resultSub").textContent=S.lang==="bn"?"দারুণ! Nutrition race শেষ।":"Great! Nutrition race complete.";const box=$("#resultStats");box.innerHTML="";S.game.playerOrder.forEach(id=>{const p=S.game.players[id],a=(p.correct+p.wrong)?Math.round(p.correct/(p.correct+p.wrong)*100):0;box.innerHTML+=`<div class="result-card"><b>${p.avatar||"🐼"} ${p.name}</b><div>Score: ${p.score}</div><div>Accuracy: ${a}%</div><div>Best streak: ${p.bestStreak}</div></div>`});$("#achievementRow").innerHTML=`<span class="badge">🏅 Race Complete</span><span class="badge">🧠 Knowledge XP</span>${w?.bestStreak>=5?'<span class="badge">🔥 Streak Master</span>':""}`}
async function authReady(){if(auth.currentUser){S.user=auth.currentUser;return S.user}await signInAnonymously(auth);return new Promise(r=>{const off=onAuthStateChanged(auth,u=>{if(u){S.user=u;off();r(u)}})})}
onAuthStateChanged(auth,u=>{S.user=u;$("#firebaseStatus").textContent=u?"Firebase connected ✓":"Firebase connecting…"});signInAnonymously(auth).catch(e=>{$("#firebaseStatus").textContent="Firebase error";$("#onlineError").textContent=e.message});
async function createRoom(){const u=await authReady(),nm=name($("#onlineName").value,"Host");let code,ex=true;for(let i=0;i<8&&ex;i++){code=roomCode();ex=(await get(ref(db,`rooms/${code}`))).exists()}if(ex)return;const cap=S.capacity;await set(ref(db,`rooms/${code}`),{hostUid:u.uid,status:"waiting",capacity:cap,settings:{level:S.level,difficulty:S.difficulty},players:{[u.uid]:{name:nm,avatar:"🐼",slot:1,ready:false,connected:true}}});enterLobby(code);presence(code)}
async function joinRoom(){const u=await authReady(),nm=name($("#onlineName").value,"Player"),code=$("#roomCodeInput").value.trim();if(!/^\d{6}$/.test(code)){return $("#onlineError").textContent="Enter a 6-digit room code."}const s=await get(ref(db,`rooms/${code}`));if(!s.exists())return $("#onlineError").textContent="Room not found.";const r=s.val(),ps=r.players||{};if(r.status!=="waiting")return $("#onlineError").textContent="Game already started.";if(!ps[u.uid]&&Object.keys(ps).length>=r.capacity)return $("#onlineError").textContent="Room is full.";const used=new Set(Object.values(ps).map(p=>p.slot)),slot=ps[u.uid]?.slot||[1,2,3,4].find(x=>!used.has(x));await set(ref(db,`rooms/${code}/players/${u.uid}`),{name:nm,avatar:"🐼",slot,ready:false,connected:true});enterLobby(code);presence(code)}
function presence(code){const p=ref(db,`rooms/${code}/players/${S.user.uid}/connected`);set(p,true);onDisconnect(p).set(false)}
function enterLobby(code){S.roomCode=code;$("#roomCodeDisplay").textContent=code;go("#lobby");if(S.unsub)S.unsub();S.unsub=onValue(ref(db,`rooms/${code}`),snap=>{if(!snap.exists()){toast("Room closed");return go("#home")}S.room=snap.val();renderLobby();if(S.room.status==="playing"&&S.room.game){S.mode="online";S.game=S.room.game;go("#game");renderBoard();renderGame();if(S.game.phase==="quiz"&&S.game.currentTurn===S.user?.uid&&$("#quizModal").classList.contains("hidden")){const q=qById(S.game.pendingQuestionId);if(q)openQuiz(q)}}if(S.room.status==="finished"&&S.room.game){S.game=S.room.game;showResult()}})}
function renderLobby(){const r=S.room,ps=Object.entries(r.players||{}).sort((a,b)=>a[1].slot-b[1].slot),w=$("#lobbyPlayers");w.innerHTML="";for(let i=1;i<=r.capacity;i++){const found=ps.find(([,p])=>p.slot===i);if(found){const [uid,p]=found;w.innerHTML+=`<div class="lobby-player"><div class="lobby-avatar">${p.avatar||"🐼"}</div><b>${p.name}</b><div class="${p.ready?"ready":"waiting"}">${p.ready?"✅ READY":"⏳ NOT READY"}</div><small>${p.connected===false?"Offline":"Online"}</small></div>`}else w.innerHTML+=`<div class="lobby-player"><div class="lobby-avatar">➕</div><b>Open Slot ${i}</b><div class="waiting">Waiting…</div></div>`}renderLobbyLevel();const mine=r.players?.[S.user?.uid];$("#readyBtn").textContent=mine?.ready?"Ready ✓":"I'm Ready";const isHost=r.hostUid===S.user?.uid,readyPlayers=ps.filter(([,p])=>p.ready).length;$("#startOnlineBtn").style.display=isHost?"inline-block":"none";$("#startOnlineBtn").disabled=ps.length<2||readyPlayers!==ps.length;$("#lobbyLevel").disabled=!isHost;$("#lobbyDifficulty").disabled=!isHost}
async function toggleReady(){const p=S.room?.players?.[S.user.uid];if(p)await update(ref(db,`rooms/${S.roomCode}/players/${S.user.uid}`),{ready:!p.ready})}
async function startOnline(){const r=S.room;if(!r||r.hostUid!==S.user.uid)return;const entries=Object.entries(r.players||{}).sort((a,b)=>a[1].slot-b[1].slot);if(entries.length<2||!entries.every(([,p])=>p.ready))return;const players=entries.map(([id,p])=>newPlayer(id,p.name,p.avatar,p.slot,false));const g=newGame({mode:"online",level:+$("#lobbyLevel").value,difficulty:$("#lobbyDifficulty").value,players});await update(ref(db,`rooms/${S.roomCode}`),{status:"playing",settings:{level:g.level,difficulty:g.difficulty},game:g})}
async function onlineRoll(){const uid=S.user.uid,d=roll(),q=question(S.game.level,S.game.difficulty,S.game.usedQuestions||[]);await runTransaction(ref(db,`rooms/${S.roomCode}/game`),g=>{if(!g||g.currentTurn!==uid||g.phase!=="roll")return;g.dice=d;const ev=move(g,uid,d);if(ev.t==="quiz"){g.pendingQuestionId=q.id;g.usedQuestions=(g.usedQuestions||[]).concat(q.id);g.phase="quiz"}else nextTurn(g);return g});await syncFinish()}
async function onlineAnswer(ok){const uid=S.user.uid;await runTransaction(ref(db,`rooms/${S.roomCode}/game`),g=>{if(!g||g.currentTurn!==uid||g.phase!=="quiz")return;quizResult(g,uid,ok);nextTurn(g);return g});await syncFinish()}
async function onlineBoost(){const uid=S.user.uid;await runTransaction(ref(db,`rooms/${S.roomCode}/game`),g=>{if(!g||g.currentTurn!==uid)return;if(useBoost(g,uid))return g});await syncFinish()}
async function syncFinish(){const s=await get(ref(db,`rooms/${S.roomCode}/game`));if(s.exists()&&s.val().status==="finished")await update(ref(db,`rooms/${S.roomCode}`),{status:"finished"})}
async function leaveRoom(){if(S.unsub){S.unsub();S.unsub=null}if(S.roomCode&&S.user){await remove(ref(db,`rooms/${S.roomCode}/players/${S.user.uid}`)).catch(()=>{})}S.roomCode=null;S.room=null;go("#home")}
$$(".mode-card").forEach(b=>b.onclick=()=>modeSetup(b.dataset.mode));$$("[data-go]").forEach(b=>b.onclick=()=>go("#"+b.dataset.go));
$("#themeBtn").onclick=()=>{S.theme=S.theme==="day"?"night":"day";setTheme()};$("#langBtn").onclick=()=>{S.lang=S.lang==="bn"?"en":"bn";applyLang()};$("#soundBtn").onclick=()=>{S.sound=!S.sound;$("#soundBtn").textContent=S.sound?"🔊":"🔇"};
$$("[data-cap]").forEach(b=>b.onclick=()=>{$$("[data-cap]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");S.capacity=+b.dataset.cap;renderNames()});$$("[data-online-cap]").forEach(b=>b.onclick=()=>{$$("[data-online-cap]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");S.capacity=+b.dataset.onlineCap});
$$("[data-diff]").forEach(b=>b.onclick=()=>{$$("[data-diff]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");S.difficulty=b.dataset.diff});
$("#startSetupBtn").onclick=startLocal;$("#rollBtn").onclick=()=>S.mode==="online"?onlineRoll():localRoll();$("#quizContinue").onclick=continueQuiz;$("#createRoomBtn").onclick=createRoom;$("#joinRoomBtn").onclick=joinRoom;$("#readyBtn").onclick=toggleReady;$("#startOnlineBtn").onclick=startOnline;$("#leaveLobbyBtn").onclick=leaveRoom;
$("#lobbyLevel").onchange=async()=>{if(S.room?.hostUid===S.user?.uid)await update(ref(db,`rooms/${S.roomCode}/settings`),{level:+$("#lobbyLevel").value})};$("#lobbyDifficulty").onchange=async()=>{if(S.room?.hostUid===S.user?.uid)await update(ref(db,`rooms/${S.roomCode}/settings`),{difficulty:$("#lobbyDifficulty").value})};
$("#homeBtn").onclick=()=>go("#home");$("#rematchBtn").onclick=()=>go("#home");
renderLevels();renderNames();applyLang();setTheme();
