import{auth,db,signInAnonymously,onAuthStateChanged,ref,set,get,update,remove,onValue,onDisconnect,runTransaction}from"./firebase.js";
import{LEVELS,QUESTIONS}from"./data.js";
import{DIFFICULTY,makePlayer,makeGame,rollDie,getQuestion,movePlayer,resolveQuiz,nextTurn,useBoost,useFreeze}from"./engine.js";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const AV=[{id:"green",name:"Nutri Panda",cls:"panda-green"},{id:"purple",name:"Berry Panda",cls:"panda-purple"},{id:"orange",name:"Sunny Panda",cls:"panda-orange"},{id:"blue",name:"Ninja Panda",cls:"panda-blue"}];
const S={lang:"bn",theme:"day",sound:true,mode:null,playerCount:4,level:1,difficulty:"medium",game:null,user:null,roomCode:null,room:null,roomUnsub:null,q:null,qAnswered:false,timer:null};
const TXT={bn:{roomNotFound:"Room পাওয়া যায়নি",roomFull:"Room পূর্ণ",gameStarted:"Game ইতিমধ্যে শুরু হয়েছে",ready:"আমি Ready",readyDone:"Ready ✓",roll:"ROLL DICE",wait:"অপেক্ষা করুন",correct:"সঠিক!",wrong:"ভুল",how:["Dice roll করে 100 নম্বর ঘরে পৌঁছান।","❓ Quiz tile-এ সঠিক উত্তর দিলে score ও streak বাড়ে।","🐍 Snake-এ পড়লে নিচে নামবেন; Shield থাকলে বাঁচতে পারবেন।","🪜 Ladder সামনে এগিয়ে দেয়।","⚡ Bonus tile power-up দেয়।","🍭 Trap tile পিছিয়ে দেয়।","যে আগে 100-তে পৌঁছাবে সে জিতবে।"]},en:{roomNotFound:"Room not found",roomFull:"Room is full",gameStarted:"Game already started",ready:"I'm Ready",readyDone:"Ready ✓",roll:"ROLL DICE",wait:"Please wait",correct:"Correct!",wrong:"Wrong",how:["Roll the dice and reach tile 100.","Correct answers on ❓ Quiz tiles increase score and streak.","🐍 Snakes move you down; a Shield can save you.","🪜 Ladders move you forward.","⚡ Bonus tiles give power-ups.","🍭 Trap tiles move you backward.","The first player to reach 100 wins."]}};
const t=k=>TXT[S.lang][k]||k;
function go(id){$$('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active')}
function toast(m){const e=$('#toast');e.textContent=m;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),1800)}
function sanitize(v,f){v=(v||'').trim().replace(/[<>]/g,'').slice(0,18);return v||f}
function levelName(n){return S.lang==='bn'?LEVELS[n].bn:LEVELS[n].en}
function pandaMarkup(id,small=false){const a=AV.find(x=>x.id===id)||AV[0];return `<div class="${small?'mini-face ':''}panda-face ${a.cls}"><span class="ear e1"></span><span class="ear e2"></span><span class="eye eye1"></span><span class="eye eye2"></span><span class="nose"></span></div>`}
function renderLevels(){const b=$('#levelPicker');b.innerHTML='';Object.keys(LEVELS).forEach(n=>{const x=document.createElement('button');x.className='level-btn'+(+n===S.level?' active':'');x.innerHTML=`<b>Level ${n}</b><small>${levelName(n)}</small>`;x.onclick=()=>{S.level=+n;renderLevels()};b.appendChild(x)})}
function renderEditor(){const w=$('#playerEditor');w.innerHTML='';const c=S.mode==='solo'?1:S.playerCount;for(let i=0;i<c;i++){const d=document.createElement('div');d.className='player-edit-card';d.innerHTML=`<b>Player ${i+1}</b><input id="pname${i}" maxlength="18" value="Player ${i+1}"><div class="avatar-choice">${AV.map((a,j)=>`<button data-p="${i}" data-avatar="${a.id}" class="${j===i%4?'active':''}" title="${a.name}">🐼</button>`).join('')}</div>`;w.appendChild(d)}$$('.avatar-choice button').forEach(b=>b.onclick=()=>{$$(`.avatar-choice button[data-p="${b.dataset.p}"]`).forEach(x=>x.classList.remove('active'));b.classList.add('active')})}
function applyLang(){$('#langBtn').textContent=S.lang==='bn'?'EN':'বাংলা';$('#homeTitle').textContent=S.lang==='bn'?'লুডুর মজা, নিউট্রিশনের জ্ঞান':'Ludo fun, nutrition knowledge';$('#homeDesc').textContent=S.lang==='bn'?'বন্ধু, কম্পিউটার বা অনলাইন রুমে ২–৪ জন খেলুন। কুইজ, পাওয়ার-আপ, স্ট্রিক আর পান্ডা অ্যানিমেশনসহ।':'Play with friends, computer or online rooms for 2–4 players with quizzes, power-ups, streaks and Panda animations.';renderLevels();if(S.game)renderGame()}
function applyTheme(){document.documentElement.dataset.theme=S.theme;$('#themeBtn').textContent=S.theme==='day'?'🌙':'☀️'}
function setup(mode){S.mode=mode;if(mode==='online'){go('#screen-online');return}$('#playerCountBlock').style.display=mode==='solo'?'none':'block';if(mode==='solo')S.playerCount=2;renderEditor();go('#screen-setup')}
function startLocal(){const ps=[];if(S.mode==='solo'){const av=$('.avatar-choice button.active')?.dataset.avatar||'green';ps.push(makePlayer('p1',sanitize($('#pname0').value,'Player 1'),1,av));ps.push(makePlayer('p2','NutriBot',2,'blue',true))}else{for(let i=0;i<S.playerCount;i++){const av=$(`.avatar-choice button[data-p="${i}"].active`)?.dataset.avatar||AV[i%4].id;ps.push(makePlayer(`p${i+1}`,sanitize($(`#pname${i}`).value,`Player ${i+1}`),i+1,av))}}S.game=makeGame({mode:S.mode,level:S.level,difficulty:S.difficulty,players:ps});enterGame()}
function boardCells(){const o=[];for(let r=9;r>=0;r--){let row=[...Array(10)].map((_,i)=>r*10+i+1);if(r%2)row.reverse();o.push(...row)}return o}
function enterGame(){go('#screen-game');buildBoard();renderGame();tone('start')}
function buildBoard(){const b=$('#board');b.innerHTML='';const L=LEVELS[S.game.level];boardCells().forEach(n=>{let cls='cell',ic='';if(L.quiz.includes(n)){cls+=' special-quiz';ic='❓'}else if(L.bonus.includes(n)){cls+=' special-bonus';ic='⚡'}else if(L.trap.includes(n)){cls+=' special-trap';ic='🍭'}else if(L.duel.includes(n)){cls+=' special-duel';ic='⚔️'}const c=document.createElement('div');c.className=cls;c.dataset.pos=n;c.innerHTML=`<span class="cell-number">${n}</span><span class="cell-icon">${ic}</span><div class="tokens"></div>`;b.appendChild(c)});requestAnimationFrame(drawOverlay)}
function center(pos){const c=$(`.cell[data-pos="${pos}"]`),b=$('#board');if(!c||!b)return{x:0,y:0};const cr=c.getBoundingClientRect(),br=b.getBoundingClientRect();return{x:((cr.left-br.left)+cr.width/2)/br.width*1000,y:((cr.top-br.top)+cr.height/2)/br.height*1000}}
function drawOverlay(){const svg=$('#boardOverlay');svg.innerHTML='';const L=LEVELS[S.game.level],ns='http://www.w3.org/2000/svg',cols=['#e85d75','#27ae60','#8e44ad','#f39c12','#3498db','#c0392b','#16a085'];let i=0;for(const [f,t]of Object.entries(L.snakes)){const a=center(+f),b=center(+t),p=document.createElementNS(ns,'path'),mx=(a.x+b.x)/2+(i%2?70:-70),my=(a.y+b.y)/2;p.setAttribute('d',`M ${a.x} ${a.y} Q ${mx} ${my} ${b.x} ${b.y}`);p.setAttribute('stroke',cols[i%cols.length]);p.setAttribute('stroke-width','18');p.setAttribute('class','snake-path');svg.appendChild(p);const h=document.createElementNS(ns,'circle');h.setAttribute('cx',a.x);h.setAttribute('cy',a.y);h.setAttribute('r','16');h.setAttribute('fill',cols[i%cols.length]);svg.appendChild(h);i++}for(const [f,t]of Object.entries(L.ladders)){const a=center(+f),b=center(+t),dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1,px=-dy/len*12,py=dx/len*12;for(const s of[1,-1]){const l=document.createElementNS(ns,'line');l.setAttribute('x1',a.x+px*s);l.setAttribute('y1',a.y+py*s);l.setAttribute('x2',b.x+px*s);l.setAttribute('y2',b.y+py*s);l.setAttribute('stroke','#8b5a2b');l.setAttribute('stroke-width','7');l.setAttribute('class','ladder-rail');svg.appendChild(l)}for(let k=1;k<=5;k++){const u=k/6,cx=a.x+(b.x-a.x)*u,cy=a.y+(b.y-a.y)*u,l=document.createElementNS(ns,'line');l.setAttribute('x1',cx+px);l.setAttribute('y1',cy+py);l.setAttribute('x2',cx-px);l.setAttribute('y2',cy-py);l.setAttribute('stroke','#c9853d');l.setAttribute('stroke-width','6');l.setAttribute('class','ladder-step');svg.appendChild(l)}}}
function currentId(){return S.mode==='online'?S.user?.uid:S.game?.currentTurn}
function canAct(){if(!S.game||S.game.status!=='playing')return false;if(S.mode==='online')return S.game.currentTurn===S.user?.uid;if(S.mode==='solo')return S.game.currentTurn==='p1';return true}
function renderStrip(){const w=$('#playersStrip');w.innerHTML='';S.game.playerOrder.forEach(id=>{const p=S.game.players[id],d=document.createElement('div');d.className='player-chip'+(id===S.game.currentTurn?' active':'');d.innerHTML=`${pandaMarkup(p.avatar,true)}<div><strong>${p.name}</strong><small>${p.position}/100 • ${p.score} pts</small></div>`;w.appendChild(d)})}
function renderTokens(anim=null){$$('.tokens').forEach(x=>x.innerHTML='');S.game.playerOrder.forEach((id,i)=>{const p=S.game.players[id],c=$(`.cell[data-pos="${Math.max(1,p.position)}"] .tokens`);if(c){const s=document.createElement('span');s.className=`token t${i+1}${anim===id?' jump':''}`;s.textContent='🐼';s.title=p.name;c.appendChild(s)}})}
function renderPower(){const p=S.game.players[currentId()],w=$('#powerups');w.innerHTML='';if(!p)return;[['shield','🛡️ Shield'],['hint','💡 Hint'],['boost','⚡ Boost'],['freeze','❄️ Freeze']].forEach(([k,l])=>{const b=document.createElement('button');b.className='power-pill';b.innerHTML=`${l} <b>${p.powerups?.[k]||0}</b>`;if(k==='boost'){b.disabled=!canAct()||!p.powerups?.boost||S.game.phase!=='roll';b.onclick=()=>S.mode==='online'?onlineBoost():localBoost()}else if(k==='freeze'){b.disabled=!canAct()||!p.powerups?.freeze||S.game.phase!=='roll';b.onclick=()=>S.mode==='online'?onlineFreeze():localFreeze()}else if(k==='hint'){b.disabled=!(S.game.phase==='quiz'&&canAct()&&p.powerups?.hint>0);b.onclick=useHint}else b.disabled=true;w.appendChild(b)})}
function orient(v){const m={1:'rotateX(0deg) rotateY(0deg)',2:'rotateY(-90deg)',3:'rotateX(-90deg)',4:'rotateX(90deg)',5:'rotateY(90deg)',6:'rotateY(180deg)'};$('#dice3d').style.transform=`${m[v]} rotateZ(${720+Math.floor(Math.random()*360)}deg)`}
function renderGame(){if(!S.game)return;const p=S.game.players[S.game.currentTurn];$('#levelMini').textContent=`LEVEL ${S.game.level}`;$('#levelName').textContent=levelName(S.game.level);$('#turnName').textContent=p?.name||'';$('#actionTitle').textContent=S.game.phase==='quiz'?'Answer the quiz':(canAct()?t('roll'):t('wait'));$('#eventLog').textContent=S.game.lastEvent||'';$('#rollBtn').disabled=!canAct()||S.game.phase!=='roll';renderStrip();renderTokens();renderPower();if(S.game.dice)orient(S.game.dice);if(S.game.status==='finished')showResult()}
function floating(txt,ico='✨'){const e=$('#floatingEvent');e.textContent=`${ico} ${txt}`;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),1050)}
function localRoll(){if(!canAct()||S.game.phase!=='roll')return;const d=rollDie();S.game.dice=d;orient(d);tone('dice');const mover=S.game.currentTurn,ev=movePlayer(S.game,mover,d);renderTokens(mover);renderGame();if(ev.type==='ladder')floating('Ladder Boost!','🪜');if(ev.type==='snake')floating('Snake Slide!','🐍');if(ev.type==='shield')floating('Shield Saved You!','🛡️');if(ev.type==='bonus')floating('Power-up!','⚡');if(ev.type==='trap')floating('Sugar Trap!','🍭');if(ev.type==='quiz'){const q=getQuestion(S.game.level,S.game.difficulty,S.game.usedQuestions);S.game.pendingQuestionId=q.id;S.game.usedQuestions.push(q.id);openQuiz(q)}else{nextTurn(S.game);renderGame();if(S.mode==='solo'&&S.game.currentTurn==='p2')setTimeout(aiTurn,800)}}
function aiTurn(){if(!S.game||S.game.currentTurn!=='p2')return;const d=rollDie();S.game.dice=d;orient(d);const ev=movePlayer(S.game,'p2',d);renderGame();if(ev.type==='quiz'){const q=getQuestion(S.game.level,S.game.difficulty,S.game.usedQuestions);S.game.usedQuestions.push(q.id);setTimeout(()=>{resolveQuiz(S.game,'p2',Math.random()<DIFFICULTY[S.game.difficulty].ai);nextTurn(S.game);renderGame()},650)}else{nextTurn(S.game);renderGame()}}
function localBoost(){if(useBoost(S.game,S.game.currentTurn)){floating('+3 Move','⚡');renderGame()}}
function localFreeze(){if(useFreeze(S.game,S.game.currentTurn)){floating('Opponent Frozen','❄️');renderGame()}}
function openQuiz(q){S.q=q;S.qAnswered=false;$('#quizModal').classList.remove('hidden');$('#quizContinueBtn').classList.add('hidden');$('#quizFeedback').textContent='';$('#quizCategory').textContent=q.category;const L=q[S.lang];$('#quizQuestion').textContent=L.q;const w=$('#quizOptions');w.innerHTML='';L.options.forEach((o,i)=>{const b=document.createElement('button');b.className='quiz-option';b.textContent=o;b.onclick=()=>answerQuiz(i);w.appendChild(b)});clearInterval(S.timer);let sec=DIFFICULTY[S.game.difficulty].timer;$('#quizTimer').textContent=sec||'∞';if(sec)S.timer=setInterval(()=>{sec--;$('#quizTimer').textContent=sec;if(sec<=0){clearInterval(S.timer);answerQuiz(-1)}},1000);renderPower()}
function useHint(){const p=S.game.players[currentId()];if(!p||p.powerups.hint<=0||!S.q)return;[0,1,2,3].filter(i=>i!==S.q.answer).slice(0,2).forEach(i=>{const b=$$('#quizOptions .quiz-option')[i];if(b){b.disabled=true;b.style.opacity='.32'}});p.powerups.hint--;renderPower();toast('💡 Two wrong options removed')}
function answerQuiz(i){if(S.qAnswered)return;S.qAnswered=true;clearInterval(S.timer);const ok=i===S.q.answer,L=S.q[S.lang];$$('#quizOptions .quiz-option').forEach((b,j)=>{b.disabled=true;if(j===S.q.answer)b.classList.add('correct');else if(j===i)b.classList.add('wrong')});$('#quizFeedback').textContent=`${ok?'✅ '+t('correct'):'❌ '+t('wrong')} ${L.explanation}`;$('#quizContinueBtn').dataset.correct=ok?'1':'0';$('#quizContinueBtn').classList.remove('hidden');tone(ok?'correct':'wrong')}
function continueQuiz(){const ok=$('#quizContinueBtn').dataset.correct==='1';$('#quizModal').classList.add('hidden');if(S.mode==='online'){onlineAnswer(ok);return}resolveQuiz(S.game,S.game.currentTurn,ok);nextTurn(S.game);renderGame();if(S.mode==='solo'&&S.game.currentTurn==='p2')setTimeout(aiTurn,750)}
function showResult(){go('#screen-result');const w=S.game.players[S.game.winner];$('#resultTitle').textContent=`${w?.name||'Winner'} Wins!`;$('#winnerAvatar').innerHTML=pandaMarkup(w?.avatar||'green');const box=$('#resultStats');box.innerHTML='';S.game.playerOrder.forEach(id=>{const p=S.game.players[id],tot=p.correct+p.wrong,acc=tot?Math.round(p.correct/tot*100):0;box.innerHTML+=`<div class="result-card"><b>${p.name}</b><div>Score: ${p.score}</div><div>Accuracy: ${acc}%</div><div>Best streak: ${p.bestStreak}</div></div>`});$('#earnedBadges').innerHTML='<span>🏁 Race Complete</span>'+(w?.bestStreak>=5?'<span>🔥 Streak Master</span>':'');saveProgress('gamesPlayed',1,true);if(w?.bestStreak>=5)saveProgress('streakMaster',1,false);confetti();tone('win')}
let audioCtx=null;function tone(type){if(!S.sound)return;try{audioCtx||=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain(),now=audioCtx.currentTime,f={dice:180,correct:520,wrong:140,power:680,start:420,win:760}[type]||300;o.connect(g);g.connect(audioCtx.destination);o.frequency.setValueAtTime(f,now);g.gain.setValueAtTime(.08,now);g.gain.exponentialRampToValueAtTime(.001,now+.3);o.start(now);o.stop(now+.31)}catch{}}
function confetti(){const c=$('#confettiCanvas'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;const p=[...Array(70)].map(()=>({x:innerWidth/2,y:innerHeight*.2,vx:(Math.random()-.5)*9,vy:-Math.random()*7-2,g:.2,r:3+Math.random()*4,a:1}));let f=0;(function draw(){x.clearRect(0,0,c.width,c.height);p.forEach(z=>{z.vy+=z.g;z.x+=z.vx;z.y+=z.vy;z.a-=.01;x.globalAlpha=Math.max(0,z.a);x.fillStyle=['#14b8a6','#f59e0b','#8b5cf6','#ef4444','#3b82f6'][Math.floor(Math.random()*5)];x.fillRect(z.x,z.y,z.r,z.r*1.6)});x.globalAlpha=1;if(f++<100)requestAnimationFrame(draw);else x.clearRect(0,0,c.width,c.height)})()}
const ACH=[['gamesPlayed','🎮 First Journey','Complete your first game'],['streakMaster','🔥 Streak Master','Reach a 5-answer streak'],['onlinePlayer','🌐 Online Explorer','Play an online room']];function progress(){try{return JSON.parse(localStorage.getItem('nutriLudoProgress')||'{}')}catch{return{}}}function saveProgress(k,a=1,inc=true){const p=progress();p[k]=inc?(p[k]||0)+a:Math.max(p[k]||0,a);localStorage.setItem('nutriLudoProgress',JSON.stringify(p))}function achievements(){const p=progress(),w=$('#achievementList');w.innerHTML='';ACH.forEach(([id,t,d])=>w.innerHTML+=`<div class="achievement-item ${p[id]?'':'locked'}"><b>${t}</b><div>${d}</div><small>${p[id]?'Unlocked':'Locked'}</small></div>`)}
async function ensureAuth(){if(auth.currentUser){S.user=auth.currentUser;return S.user}await signInAnonymously(auth);return new Promise(r=>{const off=onAuthStateChanged(auth,u=>{if(u){S.user=u;off();r(u)}})})}onAuthStateChanged(auth,u=>{S.user=u;$('#firebaseStatus').textContent=u?'Firebase connected ✓':'Connecting to Firebase…'});signInAnonymously(auth).catch(e=>{$('#firebaseStatus').textContent='Firebase error';$('#onlineError').textContent=e.message});
const roomCode=()=>String(Math.floor(100000+Math.random()*900000));async function createRoom(){const u=await ensureAuth(),nm=sanitize($('#onlineName').value,'Host');let code,ex=true;for(let i=0;i<8&&ex;i++){code=roomCode();ex=(await get(ref(db,`rooms/${code}`))).exists()}if(ex)return;await set(ref(db,`rooms/${code}`),{hostUid:u.uid,status:'waiting',capacity:S.playerCount,settings:{level:S.level,difficulty:S.difficulty},players:{[u.uid]:{name:nm,slot:1,avatar:'green',ready:false,connected:true}}});enterLobby(code);presence(code)}
async function joinRoom(){const u=await ensureAuth(),code=$('#roomCodeInput').value.trim(),nm=sanitize($('#onlineName').value,'Player');if(!/^\d{6}$/.test(code)){return $('#onlineError').textContent='Enter a 6-digit room code.'}const s=await get(ref(db,`rooms/${code}`));if(!s.exists())return $('#onlineError').textContent=t('roomNotFound');const r=s.val(),ps=r.players||{};if(r.status!=='waiting')return $('#onlineError').textContent=t('gameStarted');if(!ps[u.uid]&&Object.keys(ps).length>=r.capacity)return $('#onlineError').textContent=t('roomFull');const used=new Set(Object.values(ps).map(p=>p.slot)),slot=ps[u.uid]?.slot||[1,2,3,4].find(x=>!used.has(x)),av=AV[(slot-1)%4].id;await set(ref(db,`rooms/${code}/players/${u.uid}`),{name:nm,slot,avatar:av,ready:false,connected:true});enterLobby(code);presence(code);saveProgress('onlinePlayer',1,false)}
function presence(code){const p=ref(db,`rooms/${code}/players/${S.user.uid}/connected`);set(p,true);onDisconnect(p).set(false)}
function enterLobby(code){S.roomCode=code;$('#roomCodeDisplay').textContent=code;go('#screen-lobby');if(S.roomUnsub)S.roomUnsub();S.roomUnsub=onValue(ref(db,`rooms/${code}`),snap=>{if(!snap.exists()){toast('Room closed');return go('#screen-home')}S.room=snap.val();renderLobby();if(S.room.status==='playing'&&S.room.game){S.mode='online';S.game=S.room.game;go('#screen-game');buildBoard();renderGame();if(S.game.phase==='quiz'&&S.game.currentTurn===S.user?.uid&&$('#quizModal').classList.contains('hidden')){const q=QUESTIONS.find(x=>x.id===S.game.pendingQuestionId);if(q)openQuiz(q)}}else if(S.room.status==='finished'&&S.room.game){S.game=S.room.game;showResult()}})}
function renderLobby(){const r=S.room,es=Object.entries(r.players||{}).sort((a,b)=>a[1].slot-b[1].slot),w=$('#lobbyPlayers');w.innerHTML='';for(let slot=1;slot<=r.capacity;slot++){const f=es.find(([,p])=>p.slot===slot);if(f){const[,p]=f;w.innerHTML+=`<div class="lobby-card"><div class="mini-avatar">${pandaMarkup(p.avatar,true)}</div><b>${p.name}</b><div class="${p.ready?'status-ready':'status-wait'}">${p.ready?'✅ READY':'⏳ WAITING'}</div><small>${p.connected===false?'Offline':'Online'}</small></div>`}else w.innerHTML+=`<div class="lobby-card"><div class="mini-avatar">➕</div><b>Open Slot ${slot}</b><div class="status-wait">Waiting…</div></div>`}const host=r.hostUid===S.user?.uid,me=r.players?.[S.user?.uid];$('#readyBtn').textContent=me?.ready?t('readyDone'):t('ready');$('#startOnlineBtn').style.display=host?'block':'none';$('#lobbyLevel').disabled=!host;$('#lobbyDifficulty').disabled=!host;$('#lobbyLevel').innerHTML='';Object.keys(LEVELS).forEach(n=>{const o=document.createElement('option');o.value=n;o.textContent=`${n} — ${levelName(n)}`;$('#lobbyLevel').appendChild(o)});$('#lobbyLevel').value=r.settings?.level||1;$('#lobbyDifficulty').value=r.settings?.difficulty||'medium';$('#startOnlineBtn').disabled=es.length<2||!es.every(([,p])=>p.ready)}
async function toggleReady(){const p=S.room?.players?.[S.user.uid];if(p)await update(ref(db,`rooms/${S.roomCode}/players/${S.user.uid}`),{ready:!p.ready})}
async function startOnline(){const r=S.room;if(!r||r.hostUid!==S.user.uid)return;const es=Object.entries(r.players||{}).sort((a,b)=>a[1].slot-b[1].slot);if(es.length<2||!es.every(([,p])=>p.ready))return;const ps=es.map(([id,p])=>makePlayer(id,p.name,p.slot,p.avatar));const g=makeGame({mode:'online',level:+$('#lobbyLevel').value,difficulty:$('#lobbyDifficulty').value,players:ps});await update(ref(db,`rooms/${S.roomCode}`),{status:'playing',settings:{level:g.level,difficulty:g.difficulty},game:g})}
async function onlineRoll(){const uid=S.user.uid,d=rollDie(),q=getQuestion(S.game.level,S.game.difficulty,S.game.usedQuestions||[]);await runTransaction(ref(db,`rooms/${S.roomCode}/game`),g=>{if(!g||g.currentTurn!==uid||g.phase!=='roll')return;g.dice=d;const e=movePlayer(g,uid,d);if(e.type==='quiz'){g.pendingQuestionId=q.id;g.usedQuestions=(g.usedQuestions||[]).concat(q.id);g.phase='quiz'}else nextTurn(g);return g});await syncFinish()}
async function onlineAnswer(ok){const uid=S.user.uid;await runTransaction(ref(db,`rooms/${S.roomCode}/game`),g=>{if(!g||g.currentTurn!==uid||g.phase!=='quiz')return;resolveQuiz(g,uid,ok);nextTurn(g);return g});await syncFinish()}
async function onlineBoost(){const uid=S.user.uid;await runTransaction(ref(db,`rooms/${S.roomCode}/game`),g=>{if(!g||g.currentTurn!==uid||g.phase!=='roll')return;if(useBoost(g,uid))return g});await syncFinish()}
async function onlineFreeze(){const uid=S.user.uid;await runTransaction(ref(db,`rooms/${S.roomCode}/game`),g=>{if(!g||g.currentTurn!==uid||g.phase!=='roll')return;if(useFreeze(g,uid))return g});await syncFinish()}
async function syncFinish(){const s=await get(ref(db,`rooms/${S.roomCode}/game`));if(s.exists()&&s.val().status==='finished')await update(ref(db,`rooms/${S.roomCode}`),{status:'finished'})}
async function leaveLobby(){if(S.roomUnsub){S.roomUnsub();S.roomUnsub=null}if(S.roomCode&&S.user)await remove(ref(db,`rooms/${S.roomCode}/players/${S.user.uid}`)).catch(()=>{});S.roomCode=null;S.room=null;go('#screen-home')}
$$('.play-btn').forEach(b=>b.onclick=()=>setup(b.dataset.mode));$$('[data-back]').forEach(b=>b.onclick=()=>go('#screen-home'));$('#themeBtn').onclick=()=>{S.theme=S.theme==='day'?'night':'day';applyTheme()};$('#langBtn').onclick=()=>{S.lang=S.lang==='bn'?'en':'bn';applyLang()};$('#soundBtn').onclick=()=>{S.sound=!S.sound;$('#soundBtn').textContent=S.sound?'🔊':'🔇'};$$('[data-count]').forEach(b=>b.onclick=()=>{$$('[data-count]').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.playerCount=+b.dataset.count;renderEditor()});$$('[data-online-cap]').forEach(b=>b.onclick=()=>{$$('[data-online-cap]').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.playerCount=+b.dataset.onlineCap});$$('[data-difficulty]').forEach(b=>b.onclick=()=>{$$('[data-difficulty]').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.difficulty=b.dataset.difficulty});$('#startLocalBtn').onclick=startLocal;$('#rollBtn').onclick=()=>S.mode==='online'?onlineRoll():localRoll();$('#quizContinueBtn').onclick=continueQuiz;$('#createRoomBtn').onclick=createRoom;$('#joinRoomBtn').onclick=joinRoom;$('#readyBtn').onclick=toggleReady;$('#startOnlineBtn').onclick=startOnline;$('#leaveLobbyBtn').onclick=leaveLobby;$('#challengeBtn').onclick=()=>{S.mode='solo';S.playerCount=2;S.level=((new Date().getDate()-1)%5)+1;S.difficulty='hard';renderEditor();go('#screen-setup');toast('🎯 Daily Challenge')};$('#achievementBtn').onclick=()=>{achievements();$('#achievementModal').classList.remove('hidden')};$('#howBtn').onclick=()=>{$('#howContent').innerHTML=TXT[S.lang].how.map((x,i)=>`<div class="how-step"><b>${i+1}.</b> ${x}</div>`).join('');$('#howModal').classList.remove('hidden')};$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.add('hidden'));$('#resultHomeBtn').onclick=()=>go('#screen-home');$('#rematchBtn').onclick=()=>go('#screen-home');$('#lobbyLevel').onchange=async()=>{if(S.room?.hostUid===S.user?.uid)await update(ref(db,`rooms/${S.roomCode}/settings`),{level:+$('#lobbyLevel').value})};$('#lobbyDifficulty').onchange=async()=>{if(S.room?.hostUid===S.user?.uid)await update(ref(db,`rooms/${S.roomCode}/settings`),{difficulty:$('#lobbyDifficulty').value})};addEventListener('resize',()=>{if(S.game)drawOverlay()});renderLevels();renderEditor();applyLang();applyTheme();
