import{auth,db,signInAnonymously,onAuthStateChanged,ref,set,get,update,remove,onValue,onDisconnect,runTransaction}from"./firebase.js";
import{LEVELS,QUESTIONS,FOOD_TILES}from"./data.js";
import{DIFF,AVATARS,player,game,rollDie,question,snakePrepare,snakeMove,classicPrepare,classicMove,resolveQuiz,endTurn}from"./game-logic.js";
import{Game3D}from"./three-engine.js";

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const S={lang:"bn",theme:"day",sound:true,gameMode:"snake",playType:null,count:4,level:1,difficulty:"medium",game:null,user:null,roomCode:null,room:null,unsub:null,q:null,qAnswered:false,timer:null,renderer:null,selectable:[],busy:false};
const TEXT={bn:{hero:"এক অ্যাপে Snake Nutrition + Classic Nutrition Ludo",heroText:"3D board, animated dice, Panda tokens, food events, quiz, power-ups, Solo, Local ও Online multiplayer.",roll:"ROLL",tap:"Glowing Panda token-এ tap করুন",wait:"অপেক্ষা করুন",correct:"সঠিক!",wrong:"ভুল"},en:{hero:"Snake Nutrition + Classic Nutrition Ludo in one app",heroText:"3D boards, animated dice, Panda tokens, food events, quizzes, power-ups, Solo, Local and Online multiplayer.",roll:"ROLL",tap:"Tap a glowing Panda token",wait:"Please wait",correct:"Correct!",wrong:"Wrong"}};
const t=k=>TEXT[S.lang][k]||k;
function go(id){$$(".screen").forEach(x=>x.classList.remove("active"));$(id).classList.add("active")}
function clean(v,f){v=(v||"").trim().replace(/[<>]/g,"").slice(0,18);return v||f}
function levelName(n){return S.lang==="bn"?LEVELS[n].bn:LEVELS[n].en}
function toast(m){const e=$("#toast");e.textContent=m;e.classList.remove("hidden");setTimeout(()=>e.classList.add("hidden"),1700)}
function tone(type){if(!S.sound)return;try{window.__ac||=new(window.AudioContext||window.webkitAudioContext)();const c=window.__ac,o=c.createOscillator(),g=c.createGain(),n=c.currentTime,f={dice:180,move:360,good:680,bad:120,correct:520,wrong:110,win:820}[type]||300;o.connect(g);g.connect(c.destination);o.frequency.setValueAtTime(f,n);g.gain.setValueAtTime(.06,n);g.gain.exponentialRampToValueAtTime(.001,n+.3);o.start(n);o.stop(n+.31)}catch{}}
function applyLang(){$("#langBtn").textContent=S.lang==="bn"?"EN":"বাংলা";$("#heroTitle").textContent=t("hero");$("#heroText").textContent=t("heroText");renderLevels();if(S.game)renderGame()}
function applyTheme(){document.documentElement.dataset.theme=S.theme;$("#themeBtn").textContent=S.theme==="day"?"🌙":"☀️"}
function renderLevels(){const b=$("#levelPicker");b.innerHTML="";Object.keys(LEVELS).forEach(n=>{const x=document.createElement("button");x.className="level-btn"+(+n===S.level?" active":"");x.innerHTML=`<b>Level ${n}</b><small>${levelName(n)}</small>`;x.onclick=()=>{S.level=+n;renderLevels()};b.appendChild(x)})}
function renderEditor(){const b=$("#playerEditor");b.innerHTML="";const c=S.playType==="solo"?1:S.count;for(let i=0;i<c;i++){const d=document.createElement("div");d.className="player-edit";d.innerHTML=`<b>Player ${i+1}</b><input id="pname${i}" value="Player ${i+1}" maxlength="18"><div class="avatars">${AVATARS.map((a,j)=>`<button data-p="${i}" data-a="${a}" class="${j===i%4?"active":""}">🐼</button>`).join("")}</div>`;b.appendChild(d)}$$(".avatars button").forEach(x=>x.onclick=()=>{$$(`.avatars button[data-p="${x.dataset.p}"]`).forEach(y=>y.classList.remove("active"));x.classList.add("active")})}
function choosePlay(type){S.playType=type;if(type==="online"){go("#onlineScreen");return}$("#playerCountBlock").style.display=type==="solo"?"none":"block";if(type==="solo")S.count=2;$("#chosenModeText").textContent=S.gameMode==="snake"?"Snake Nutrition":"Classic Nutrition Ludo";renderEditor();go("#setupScreen")}
function startLocal(){const ps=[];if(S.playType==="solo"){const av=$(".avatars button.active")?.dataset.a||"green";ps.push(player("p1",clean($("#pname0").value,"Player 1"),1,av));ps.push(player("p2","NutriBot",2,"blue",true))}else{for(let i=0;i<S.count;i++){const av=$(`.avatars button[data-p="${i}"].active`)?.dataset.a||AVATARS[i%4];ps.push(player(`p${i+1}`,clean($(`#pname${i}`).value,`Player ${i+1}`),i+1,av))}}S.game=game({mode:S.gameMode,playType:S.playType,level:S.level,difficulty:S.difficulty,players:ps});enterGame()}
function enterGame(){go("#gameScreen");S.renderer||=(new Game3D($("#gameCanvas")));S.game.mode==="snake"?S.renderer.buildSnake(S.game):S.renderer.buildClassic(S.game);renderGame()}
function canAct(){if(!S.game||S.game.status!=="playing")return false;if(S.playType==="online")return S.game.currentTurn===S.user?.uid;if(S.playType==="solo")return S.game.currentTurn==="p1";return true}
function renderPlayers(){const b=$("#playersBar");b.innerHTML="";S.game.order.forEach(id=>{const p=S.game.players[id],state=S.game.mode==="snake"?(p.snake.inYard?"HOME":p.snake.pos+"/100"):`${p.classic.tokens.filter(x=>x.p>=56).length}/4 HOME`;b.innerHTML+=`<div class="player-chip ${id===S.game.currentTurn?"active":""}"><span class="p">🐼</span><div><b>${p.name}</b><small>${state} • ${p.score} pts</small></div></div>`})}
function renderPower(){const b=$("#powerups");b.innerHTML="";const p=S.game.players[S.playType==="online"?S.user?.uid:S.game.currentTurn];if(!p)return;[["hint","💡 Hint"],["boost","⚡ Boost"],["freeze","❄️ Freeze"]].forEach(([k,l])=>{const x=document.createElement("button");x.className="power-pill";x.textContent=`${l} ${p.powerups[k]||0}`;x.disabled=k!=="hint"||!(S.game.phase==="quiz"&&canAct()&&p.powerups.hint);if(k==="hint")x.onclick=useHint;b.appendChild(x)})}
function renderGame(){if(!S.game)return;const p=S.game.players[S.game.currentTurn];$("#modeBadge").textContent=S.game.mode==="snake"?"SNAKE NUTRITION":"CLASSIC NUTRITION LUDO";$("#levelTitle").textContent=levelName(S.game.level);$("#turnName").textContent=p.name;$("#lastRoll").textContent=S.game.dice??"—";$("#instructionTitle").textContent=S.game.phase==="select"?t("tap"):(canAct()?t("roll"):t("wait"));$("#instructionSub").textContent=S.game.lastEvent||"";$("#rollBtn").disabled=!canAct()||S.game.phase!=="roll"||S.busy;$("#selectHint").classList.toggle("hidden",S.game.phase!=="select");renderPlayers();renderPower();S.renderer?.sync(S.game);S.renderer?.highlight(S.selectable);if(S.game.status==="finished")showResult()}
async function rollLocal(){if(!canAct()||S.game.phase!=="roll")return;S.busy=true;const d=rollDie();S.game.dice=d;await S.renderer.rollDice(d);showRoll(d,S.game.players[S.game.currentTurn].name);tone("dice");const prep=S.game.mode==="snake"?snakePrepare(S.game,S.game.currentTurn,d):classicPrepare(S.game,S.game.currentTurn,d);S.selectable=(prep.selectable||[]).map(i=>({uid:S.game.currentTurn,idx:i}));S.busy=false;renderGame();if(!S.selectable.length)setTimeout(()=>endLocalTurn(),700)}
function showRoll(v,who){$("#rollWho").textContent=`${who} ROLLED`;$("#rollValue").textContent=v;$("#rollBadge").classList.remove("hidden");setTimeout(()=>$("#rollBadge").classList.add("hidden"),1500)}
async function onCanvasTap(ev){if(!S.game||S.game.phase!=="select")return;const hit=S.renderer.pickToken(ev.clientX,ev.clientY);if(!hit)return;const valid=S.selectable.some(s=>s.uid===hit.uid&&s.idx===hit.idx);if(!valid)return;if(S.playType==="online"){await onlineToken(hit.idx);return}S.busy=true;const out=S.game.mode==="snake"?snakeMove(S.game,hit.uid):classicMove(S.game,hit.uid,hit.idx);S.selectable=[];S.renderer.sync(S.game);tone("move");await handleOutcome(out);S.busy=false;if(out.type==="quiz"){const q=question(S.game.level,S.game.difficulty,S.game.usedQuestions);S.game.pendingQuestionId=q.id;S.game.usedQuestions.push(q.id);openQuiz(q)}else if(S.game.status!=="finished")endLocalTurn();else renderGame()}
async function handleOutcome(out){if(out.type!=="food")return;const f=out.food;$("#eventIcon").textContent=f.icon;$("#eventTitle").textContent=S.lang==="bn"?f.bn:f.en;$("#eventText").textContent=`${f.delta>0?"+":""}${f.delta} ${f.kind==="good"?"Healthy boost":"Move back"}`;$("#eventPopup").classList.remove("hidden");tone(f.kind==="good"?"good":"bad");await new Promise(r=>setTimeout(r,950));$("#eventPopup").classList.add("hidden");S.renderer.sync(S.game)}
function endLocalTurn(){endTurn(S.game);S.selectable=[];renderGame();if(S.playType==="solo"&&S.game.currentTurn==="p2")setTimeout(aiTurn,750)}
async function aiTurn(){if(!S.game||S.game.currentTurn!=="p2")return;S.busy=true;const d=rollDie();S.game.dice=d;await S.renderer.rollDice(d);showRoll(d,"COMPUTER");const prep=S.game.mode==="snake"?snakePrepare(S.game,"p2",d):classicPrepare(S.game,"p2",d);if(!prep.selectable?.length){S.busy=false;return setTimeout(endLocalTurn,500)}const idx=prep.selectable[Math.floor(Math.random()*prep.selectable.length)];const out=S.game.mode==="snake"?snakeMove(S.game,"p2"):classicMove(S.game,"p2",idx);S.renderer.sync(S.game);await handleOutcome(out);if(out.type==="quiz"){const q=question(S.game.level,S.game.difficulty,S.game.usedQuestions);const ok=Math.random()<DIFF[S.game.difficulty].ai;resolveQuiz(S.game,"p2",ok)}S.busy=false;if(S.game.status!=="finished")endLocalTurn();else renderGame()}
function openQuiz(q){S.q=q;S.qAnswered=false;$("#quizModal").classList.remove("hidden");$("#quizContinueBtn").classList.add("hidden");$("#quizFeedback").textContent="";$("#quizCategory").textContent=q.category;const L=q[S.lang];$("#quizQuestion").textContent=L.q;const b=$("#quizOptions");b.innerHTML="";L.options.forEach((o,i)=>{const x=document.createElement("button");x.className="quiz-option";x.textContent=o;x.onclick=()=>answerQuiz(i);b.appendChild(x)});clearInterval(S.timer);let sec=DIFF[S.game.difficulty].timer;$("#quizTimer").textContent=sec||"∞";if(sec)S.timer=setInterval(()=>{sec--;$("#quizTimer").textContent=sec;if(sec<=0){clearInterval(S.timer);answerQuiz(-1)}},1000)}
function answerQuiz(i){if(S.qAnswered)return;S.qAnswered=true;clearInterval(S.timer);const ok=i===S.q.answer,L=S.q[S.lang];$$(".quiz-option").forEach((b,j)=>{b.disabled=true;if(j===S.q.answer)b.classList.add("correct");else if(j===i)b.classList.add("wrong")});$("#quizFeedback").textContent=`${ok?"✅ "+t("correct"):"❌ "+t("wrong")} ${L.explanation}`;$("#quizContinueBtn").dataset.ok=ok?"1":"0";$("#quizContinueBtn").classList.remove("hidden");tone(ok?"correct":"wrong")}
function useHint(){const p=S.game.players[S.playType==="online"?S.user.uid:S.game.currentTurn];if(!p?.powerups.hint||!S.q)return;[0,1,2,3].filter(i=>i!==S.q.answer).slice(0,2).forEach(i=>{const b=$$(".quiz-option")[i];if(b){b.disabled=true;b.style.opacity=".3"}});p.powerups.hint--;renderPower()}
function continueQuiz(){const ok=$("#quizContinueBtn").dataset.ok==="1";$("#quizModal").classList.add("hidden");if(S.playType==="online"){onlineQuiz(ok);return}resolveQuiz(S.game,S.game.currentTurn,ok);endLocalTurn()}
function showResult(){go("#resultScreen");const w=S.game.players[S.game.winner];$("#resultTitle").textContent=`${w.name} Wins!`;const b=$("#resultStats");b.innerHTML="";S.game.order.forEach(id=>{const p=S.game.players[id],tot=p.correct+p.wrong,acc=tot?Math.round(p.correct/tot*100):0;b.innerHTML+=`<div class="stat-card"><b>${p.name}</b><div>Score ${p.score}</div><div>Accuracy ${acc}%</div><div>Best streak ${p.bestStreak}</div></div>`});$("#resultBadges").innerHTML=`<span>🏁 Race Complete</span>${w.bestStreak>=5?"<span>🔥 Streak Master</span>":""}`;confetti();saveProgress("games",1)}
function confetti(){const c=$("#confettiCanvas"),x=c.getContext("2d");c.width=innerWidth;c.height=innerHeight;const p=[...Array(80)].map(()=>({x:innerWidth/2,y:innerHeight*.18,vx:(Math.random()-.5)*9,vy:-Math.random()*7-2,g:.2,a:1,r:3+Math.random()*4}));let f=0;(function d(){x.clearRect(0,0,c.width,c.height);p.forEach(z=>{z.vy+=z.g;z.x+=z.vx;z.y+=z.vy;z.a-=.01;x.globalAlpha=Math.max(0,z.a);x.fillStyle=["#14b8a6","#f59e0b","#8b5cf6","#ef4444","#3b82f6"][Math.floor(Math.random()*5)];x.fillRect(z.x,z.y,z.r,z.r*1.5)});x.globalAlpha=1;if(f++<100)requestAnimationFrame(d)})()}
function progress(){try{return JSON.parse(localStorage.getItem("nutriWorldProgress")||"{}")}catch{return{}}}function saveProgress(k,a=1){const p=progress();p[k]=(p[k]||0)+a;localStorage.setItem("nutriWorldProgress",JSON.stringify(p))}
function showAchievements(){const p=progress();$("#achievementList").innerHTML=`<div class="achievement-item ${p.games?"":"locked"}"><b>🎮 First Journey</b><div>Complete one game</div></div><div class="achievement-item ${p.online?"":"locked"}"><b>🌐 Online Explorer</b><div>Play online</div></div>`}
function showHow(){$("#howContent").innerHTML=[S.lang==="bn"?"Snake mode: ১ বা ৬ উঠলে Panda board-এ ঢুকবে।":"Snake mode: roll 1 or 6 to enter.",S.lang==="bn"?"Classic mode: প্রতি player-এর ৪টি Panda token।":"Classic mode: four Panda tokens per player.",S.lang==="bn"?"Dice roll-এর পর glowing token-এ tap করে move করুন।":"After rolling, tap a glowing token.",S.lang==="bn"?"🥦 Healthy food সামনে নেয়, 🍔 junk food পিছিয়ে দেয়।":"Healthy food moves forward; junk food moves back.",S.lang==="bn"?"❓ Quiz tile-এ nutrition question আসবে।":"Quiz tiles open a nutrition question."].map((x,i)=>`<div class="how-step"><b>${i+1}.</b> ${x}</div>`).join("")}

/* Firebase */
async function ensureAuth(){if(auth.currentUser){S.user=auth.currentUser;return S.user}await signInAnonymously(auth);return new Promise(r=>{const off=onAuthStateChanged(auth,u=>{if(u){S.user=u;off();r(u)}})})}
onAuthStateChanged(auth,u=>{S.user=u;$("#firebaseStatus").textContent=u?"Firebase connected ✓":"Connecting…"});signInAnonymously(auth).catch(e=>{$("#firebaseStatus").textContent="Firebase error";$("#onlineError").textContent=e.message});
const roomCode=()=>String(Math.floor(100000+Math.random()*900000));
async function createRoom(){const u=await ensureAuth(),nm=clean($("#onlineName").value,"Host");let code,ex=true;for(let i=0;i<8&&ex;i++){code=roomCode();ex=(await get(ref(db,`rooms/${code}`))).exists()}if(ex)return;await set(ref(db,`rooms/${code}`),{hostUid:u.uid,status:"waiting",capacity:S.count,settings:{mode:S.gameMode,level:S.level,difficulty:S.difficulty},players:{[u.uid]:{name:nm,slot:1,avatar:"green",ready:false,connected:true}}});enterLobby(code);presence(code)}
async function joinRoom(){const u=await ensureAuth(),code=$("#roomCodeInput").value.trim(),nm=clean($("#onlineName").value,"Player");if(!/^\d{6}$/.test(code))return $("#onlineError").textContent="Enter a 6-digit room code.";const snap=await get(ref(db,`rooms/${code}`));if(!snap.exists())return $("#onlineError").textContent="Room not found.";const r=snap.val(),ps=r.players||{};if(r.status!=="waiting")return $("#onlineError").textContent="Game already started.";if(!ps[u.uid]&&Object.keys(ps).length>=r.capacity)return $("#onlineError").textContent="Room full.";const used=new Set(Object.values(ps).map(p=>p.slot)),slot=ps[u.uid]?.slot||[1,2,3,4].find(x=>!used.has(x));await set(ref(db,`rooms/${code}/players/${u.uid}`),{name:nm,slot,avatar:AVATARS[(slot-1)%4],ready:false,connected:true});enterLobby(code);presence(code);saveProgress("online",1)}
function presence(code){const p=ref(db,`rooms/${code}/players/${S.user.uid}/connected`);set(p,true);onDisconnect(p).set(false)}
function enterLobby(code){S.roomCode=code;$("#roomCodeDisplay").textContent=code;go("#lobbyScreen");if(S.unsub)S.unsub();S.unsub=onValue(ref(db,`rooms/${code}`),snap=>{if(!snap.exists()){toast("Room closed");return go("#homeScreen")}S.room=snap.val();renderLobby();if(S.room.status==="playing"&&S.room.game){S.playType="online";S.game=S.room.game;enterGame();if(S.game.phase==="quiz"&&S.game.currentTurn===S.user?.uid&&$("#quizModal").classList.contains("hidden")){const q=QUESTIONS.find(x=>x.id===S.game.pendingQuestionId);if(q)openQuiz(q)}}else if(S.room.status==="finished"&&S.room.game){S.game=S.room.game;showResult()}})}
function renderLobby(){const r=S.room,es=Object.entries(r.players||{}).sort((a,b)=>a[1].slot-b[1].slot),b=$("#lobbyPlayers");b.innerHTML="";for(let s=1;s<=r.capacity;s++){const f=es.find(([,p])=>p.slot===s);b.innerHTML+=f?`<div class="lobby-player"><div class="face">🐼</div><b>${f[1].name}</b><div>${f[1].ready?"✅ READY":"⏳ WAIT"}</div></div>`:`<div class="lobby-player"><div class="face">➕</div><b>Open ${s}</b></div>`}const host=r.hostUid===S.user?.uid,me=r.players?.[S.user?.uid];$("#readyBtn").textContent=me?.ready?"READY ✓":"I'M READY";$("#startOnlineBtn").style.display=host?"block":"none";$("#startOnlineBtn").disabled=es.length<2||!es.every(([,p])=>p.ready);$("#lobbyMode").disabled=!host;$("#lobbyLevel").disabled=!host;$("#lobbyDifficulty").disabled=!host;$("#lobbyMode").value=r.settings?.mode||"snake";$("#lobbyLevel").innerHTML="";Object.keys(LEVELS).forEach(n=>{const o=document.createElement("option");o.value=n;o.textContent=`${n} — ${levelName(n)}`;$("#lobbyLevel").appendChild(o)});$("#lobbyLevel").value=r.settings?.level||1;$("#lobbyDifficulty").value=r.settings?.difficulty||"medium"}
async function toggleReady(){const p=S.room?.players?.[S.user.uid];if(p)await update(ref(db,`rooms/${S.roomCode}/players/${S.user.uid}`),{ready:!p.ready})}
async function startOnline(){const r=S.room;if(!r||r.hostUid!==S.user.uid)return;const es=Object.entries(r.players||{}).sort((a,b)=>a[1].slot-b[1].slot);if(es.length<2||!es.every(([,p])=>p.ready))return;const ps=es.map(([id,p])=>player(id,p.name,p.slot,p.avatar));const g=game({mode:$("#lobbyMode").value,playType:"online",level:+$("#lobbyLevel").value,difficulty:$("#lobbyDifficulty").value,players:ps});await update(ref(db,`rooms/${S.roomCode}`),{status:"playing",game:g,settings:{mode:g.mode,level:g.level,difficulty:g.difficulty}})}
async function onlineRoll(){if(!canAct()||S.game.phase!=="roll")return;const d=rollDie();await S.renderer.rollDice(d);showRoll(d,S.game.players[S.game.currentTurn].name);const q=question(S.game.level,S.game.difficulty,S.game.usedQuestions||[]);await runTransaction(ref(db,`rooms/${S.roomCode}/game`),g=>{if(!g||g.currentTurn!==S.user.uid||g.phase!=="roll")return;g.dice=d;const prep=g.mode==="snake"?snakePrepare(g,S.user.uid,d):classicPrepare(g,S.user.uid,d);if(!prep.selectable?.length)endTurn(g);return g});}
async function onlineToken(idx){const q=question(S.game.level,S.game.difficulty,S.game.usedQuestions||[]);await runTransaction(ref(db,`rooms/${S.roomCode}/game`),g=>{if(!g||g.currentTurn!==S.user.uid||g.phase!=="select")return;const out=g.mode==="snake"?snakeMove(g,S.user.uid):classicMove(g,S.user.uid,idx);if(out.type==="quiz"){g.pendingQuestionId=q.id;g.usedQuestions=(g.usedQuestions||[]).concat(q.id)}else if(g.status!=="finished")endTurn(g);return g});await syncFinish()}
async function onlineQuiz(ok){await runTransaction(ref(db,`rooms/${S.roomCode}/game`),g=>{if(!g||g.currentTurn!==S.user.uid||g.phase!=="quiz")return;resolveQuiz(g,S.user.uid,ok);if(g.status!=="finished")endTurn(g);return g});await syncFinish()}
async function syncFinish(){const s=await get(ref(db,`rooms/${S.roomCode}/game`));if(s.exists()&&s.val().status==="finished")await update(ref(db,`rooms/${S.roomCode}`),{status:"finished"})}
async function leaveRoom(){if(S.unsub){S.unsub();S.unsub=null}if(S.roomCode&&S.user)await remove(ref(db,`rooms/${S.roomCode}/players/${S.user.uid}`)).catch(()=>{});S.roomCode=null;S.room=null;go("#homeScreen")}

/* Events */
$$("[data-game-mode]").forEach(b=>b.onclick=()=>{$$("[data-game-mode]").forEach(x=>x.classList.remove("active"));b.classList.add("active");S.gameMode=b.dataset.gameMode});
$$("[data-play]").forEach(b=>b.onclick=()=>choosePlay(b.dataset.play));$$("[data-back]").forEach(b=>b.onclick=()=>go("#homeScreen"));
$("#themeBtn").onclick=()=>{S.theme=S.theme==="day"?"night":"day";applyTheme()};$("#langBtn").onclick=()=>{S.lang=S.lang==="bn"?"en":"bn";applyLang()};$("#soundBtn").onclick=()=>{S.sound=!S.sound;$("#soundBtn").textContent=S.sound?"🔊":"🔇"};
$$("[data-count]").forEach(b=>b.onclick=()=>{$$("[data-count]").forEach(x=>x.classList.remove("active"));b.classList.add("active");S.count=+b.dataset.count;renderEditor()});$$("[data-online-count]").forEach(b=>b.onclick=()=>{$$("[data-online-count]").forEach(x=>x.classList.remove("active"));b.classList.add("active");S.count=+b.dataset.onlineCount});$$("[data-diff]").forEach(b=>b.onclick=()=>{$$("[data-diff]").forEach(x=>x.classList.remove("active"));b.classList.add("active");S.difficulty=b.dataset.diff});
$("#startLocalBtn").onclick=startLocal;$("#rollBtn").onclick=()=>S.playType==="online"?onlineRoll():rollLocal();$("#gameCanvas").addEventListener("pointerup",onCanvasTap);$("#quizContinueBtn").onclick=continueQuiz;$("#createRoomBtn").onclick=createRoom;$("#joinRoomBtn").onclick=joinRoom;$("#readyBtn").onclick=toggleReady;$("#startOnlineBtn").onclick=startOnline;$("#leaveRoomBtn").onclick=leaveRoom;$("#homeBtn").onclick=()=>go("#homeScreen");$("#againBtn").onclick=()=>go("#homeScreen");$("#howBtn").onclick=()=>{showHow();$("#howModal").classList.remove("hidden")};$("#achievementBtn").onclick=()=>{showAchievements();$("#achievementModal").classList.remove("hidden")};$("#challengeBtn").onclick=()=>{S.gameMode="snake";S.playType="solo";S.level=((new Date().getDate()-1)%5)+1;S.difficulty="hard";renderEditor();go("#setupScreen");toast("🎯 Daily Challenge")};$$("[data-close]").forEach(b=>b.onclick=()=>$("#"+b.dataset.close).classList.add("hidden"));
$("#lobbyMode").onchange=async()=>{if(S.room?.hostUid===S.user?.uid)await update(ref(db,`rooms/${S.roomCode}/settings`),{mode:$("#lobbyMode").value})};$("#lobbyLevel").onchange=async()=>{if(S.room?.hostUid===S.user?.uid)await update(ref(db,`rooms/${S.roomCode}/settings`),{level:+$("#lobbyLevel").value})};$("#lobbyDifficulty").onchange=async()=>{if(S.room?.hostUid===S.user?.uid)await update(ref(db,`rooms/${S.roomCode}/settings`),{difficulty:$("#lobbyDifficulty").value})};

$('[data-game-mode="snake"]').classList.add("active");renderLevels();renderEditor();applyLang();applyTheme();
