import {CLASSIC_CONFIG,globalCell,HOME_LANES,CLASSIC_SPECIALS} from './classic-map.js';
export function newClassicPlayer(id,name,slot,color,isAI=false){return{id,name,slot,color,isAI,score:0,correct:0,wrong:0,bestStreak:0,quizStreak:0,powers:{shield:0,hint:1,boost:0},tokens:[0,1,2,3].map(i=>({id:`${color}-${i}`,state:-1}))};}
export function tokenCell(player,token){if(token.state<0)return null;if(token.state<=50)return{kind:'common',global:globalCell(player.color,token.state)};if(token.state<=56)return{kind:'home',index:token.state-51,coord:HOME_LANES[player.color][token.state-51]};return{kind:'finished',coord:[7,7]};}
function blockadeOwners(game,global){const groups={};for(const pid of game.order){const p=game.players[pid];const n=p.tokens.filter(t=>tokenCell(p,t)?.kind==='common'&&tokenCell(p,t).global===global).length;if(n>=2)groups[pid]=n;}return groups;}
function passesEnemyBlock(game,p,state,dice){for(let i=1;i<=dice;i++){const n=state+i;if(n>50)break;const g=globalCell(p.color,n),owners=blockadeOwners(game,g);if(Object.keys(owners).some(pid=>pid!==p.id))return true;}return false;}
export function legalClassicMoves(game,playerId,dice){const p=game.players[playerId],moves=[];for(let i=0;i<p.tokens.length;i++){const t=p.tokens[i],s=t.state;if(s===57)continue;if(s===-1){if(dice===CLASSIC_CONFIG.openingNumber){const dest=CLASSIC_CONFIG.startOffsets[p.color],owners=blockadeOwners(game,dest);if(!Object.keys(owners).some(pid=>pid!==playerId))moves.push({tokenIndex:i,type:'open',from:-1,to:0,global:dest});}continue;}const next=s+dice;if(next>57)continue;if(passesEnemyBlock(game,p,s,dice))continue;let canCapture=false,destGlobal=null;if(next<=50){destGlobal=globalCell(p.color,next);if(!CLASSIC_CONFIG.safeCells.includes(destGlobal)){canCapture=game.order.some(pid=>{if(pid===playerId)return false;const op=game.players[pid],n=op.tokens.filter(tok=>tokenCell(op,tok)?.kind==='common'&&tokenCell(op,tok).global===destGlobal).length;return n===1;});}}moves.push({tokenIndex:i,type:'move',from:s,to:next,global:destGlobal,canCapture,entersHome:s<=50&&next>=51,finishes:next===57});}return moves;}
export function applyClassicMove(game,playerId,tokenIndex,dice){const move=legalClassicMoves(game,playerId,dice).find(m=>m.tokenIndex===tokenIndex);if(!move)throw new Error('Illegal move');const p=game.players[playerId],t=p.tokens[tokenIndex];t.state=move.to;const events=[];if(move.type==='open')events.push({type:'OPEN'});if(move.finishes)events.push({type:'FINISH_TOKEN'});if(move.to<=50){const global=globalCell(p.color,move.to);if(!CLASSIC_CONFIG.safeCells.includes(global)){for(const oid of game.order){if(oid===playerId)continue;const op=game.players[oid],victims=op.tokens.filter(tok=>tokenCell(op,tok)?.kind==='common'&&tokenCell(op,tok).global===global);if(victims.length===1){if(op.powers.shield>0){op.powers.shield--;events.push({type:'SHIELD_BLOCK',playerId:oid});}else{victims[0].state=-1;events.push({type:'CAPTURE',playerId:oid,tokenId:victims[0].id});}}}}const special=classicSpecialAt(global);if(special)events.push(special);}return{move,events};}
export function classicSpecialAt(global){if(CLASSIC_SPECIALS.quiz.includes(global))return{type:'QUIZ',cell:global};if(CLASSIC_SPECIALS.healthy[global])return{type:'HEALTHY',cell:global,data:CLASSIC_SPECIALS.healthy[global]};if(CLASSIC_SPECIALS.junk[global])return{type:'JUNK',cell:global,data:CLASSIC_SPECIALS.junk[global]};if(CLASSIC_SPECIALS.bonus[global])return{type:'POWER',cell:global,data:CLASSIC_SPECIALS.bonus[global]};return null;}
export function applyClassicSpecial(game,playerId,event){const p=game.players[playerId],e=event.data?.effect;if(!e)return;if(e.type==='score')p.score=Math.max(0,p.score+e.value);if(e.type==='shield')p.powers.shield=Math.max(0,p.powers.shield+e.value);if(e.type==='hint')p.powers.hint+=e.value;if(e.type==='boost')p.powers.boost+=e.value;}
export function classicWinner(game,playerId){return game.players[playerId].tokens.every(t=>t.state===57);}
