import{LEVELS,QUESTIONS}from"./data.js";
export const DIFFICULTY={easy:{timer:0,points:10,penalty:0,ai:.58},medium:{timer:25,points:15,penalty:1,ai:.75},hard:{timer:15,points:25,penalty:2,ai:.89}};
export function makePlayer(id,name,slot,avatar,isAI=false){return{id,name,slot,avatar,isAI,position:0,score:0,xp:0,streak:0,bestStreak:0,correct:0,wrong:0,powerups:{shield:1,hint:1,boost:0,freeze:1}}}
export function makeGame({mode,level,difficulty,players}){const map={};players.forEach(p=>map[p.id]=p);return{mode,level,difficulty,status:"playing",phase:"roll",turnIndex:0,currentTurn:players[0].id,playerOrder:players.map(p=>p.id),players:map,dice:null,pendingQuestionId:null,usedQuestions:[],lastEvent:"Game started",winner:null,frozen:{}}}
export const rollDie=()=>Math.floor(Math.random()*6)+1;
export function getQuestion(level,difficulty,used=[]){let pool=QUESTIONS.filter(q=>q.level===Number(level)&&q.difficulty===difficulty&&!used.includes(q.id));if(!pool.length)pool=QUESTIONS.filter(q=>q.level===Number(level)&&!used.includes(q.id));if(!pool.length)pool=QUESTIONS.filter(q=>q.level===Number(level));return pool[Math.floor(Math.random()*pool.length)]}
export function getTileEvent(level,pos){const L=LEVELS[level];if(L.ladders[pos])return{type:"ladder",to:Number(L.ladders[pos])};if(L.snakes[pos])return{type:"snake",to:Number(L.snakes[pos])};if(L.quiz.includes(pos))return{type:"quiz"};if(L.bonus.includes(pos))return{type:"bonus"};if(L.trap.includes(pos))return{type:"trap"};if(L.duel.includes(pos))return{type:"duel"};return{type:"normal"}}
export function movePlayer(game,uid,dice){const p=game.players[uid];let target=p.position+dice;if(target>100)target=p.position;p.position=target;const e=getTileEvent(game.level,target);if(e.type==="ladder"){p.position=e.to;game.lastEvent=`${p.name} climbed the ladder to ${e.to}!`}else if(e.type==="snake"){if(p.powerups.shield>0){p.powerups.shield--;game.lastEvent=`${p.name}'s shield blocked the snake!`;return{type:"shield"}}p.position=e.to;game.lastEvent=`${p.name} slid down to ${e.to}!`}else if(e.type==="bonus"){p.powerups.boost++;p.score+=10;game.lastEvent=`${p.name} found a Nutrition Boost!`}else if(e.type==="trap"){p.position=Math.max(0,p.position-3);game.lastEvent=`${p.name} hit a Sugar Trap and moved back 3.`}else if(e.type==="duel"){game.phase="quiz";game.lastEvent=`${p.name} landed on a Duel tile!`;return{type:"quiz",duel:true}}else if(e.type==="quiz"){game.phase="quiz"}else game.lastEvent=`${p.name} moved to ${p.position}.`;return e}
export function resolveQuiz(game,uid,correct){const p=game.players[uid],cfg=DIFFICULTY[game.difficulty];if(correct){p.correct++;p.streak++;p.bestStreak=Math.max(p.bestStreak,p.streak);const sm=Math.min(3,Math.floor(p.streak/3));p.score+=cfg.points+sm*5;p.xp+=cfg.points;if(sm)p.position=Math.min(100,p.position+sm);game.lastEvent=`Correct! ${p.name} earned ${cfg.points+sm*5} points${sm?` and +${sm} move`:""}.`}else{p.wrong++;p.streak=0;if(cfg.penalty)p.position=Math.max(0,p.position-cfg.penalty);game.lastEvent=`Wrong answer. ${p.name}${cfg.penalty?` moved back ${cfg.penalty}`:" stays here"}.`}game.phase="roll";game.pendingQuestionId=null}
export function nextTurn(game){if(game.status!=="playing")return;const p=game.players[game.currentTurn];if(p.position>=100){game.status="finished";game.winner=p.id;return}let tries=0;do{game.turnIndex=(game.turnIndex+1)%game.playerOrder.length;game.currentTurn=game.playerOrder[game.turnIndex];tries++;const f=game.frozen?.[game.currentTurn]||0;if(f>0){game.frozen[game.currentTurn]=f-1;game.lastEvent=`${game.players[game.currentTurn].name}'s turn was frozen!`;continue}break}while(tries<=game.playerOrder.length);game.dice=null;game.phase="roll"}
export function useBoost(game,uid){const p=game.players[uid];if(!p.powerups.boost)return false;p.powerups.boost--;p.position=Math.min(100,p.position+3);p.score+=5;game.lastEvent=`${p.name} used Nutrition Boost (+3)!`;return true}
export function useFreeze(game,uid){const p=game.players[uid];if(!p.powerups.freeze)return false;const opponents=game.playerOrder.filter(id=>id!==uid),target=opponents[game.turnIndex%opponents.length];p.powerups.freeze--;game.frozen[target]=(game.frozen[target]||0)+1;game.lastEvent=`${p.name} froze ${game.players[target].name}'s next turn!`;return true}
