import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import {CLASSIC_TRACK,CLASSIC_CONFIG,HOME_LANES,CLASSIC_SPECIALS,globalCell} from '../classic/classic-map.js';
import {SNAKE_CONFIG,tileCoord} from '../snake/snake-map.js';
export class GameRenderer{
 constructor(canvas){this.canvas=canvas;this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));this.renderer.shadowMap.enabled=true;this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(42,1,.1,100);this.root=new THREE.Group();this.scene.add(this.root);this.tokens=new Map();this.selectable=[];this.mode='classic';this.dice=null;this.scene.add(new THREE.HemisphereLight(0xffffff,0x264c43,1.8));const d=new THREE.DirectionalLight(0xffffff,2);d.position.set(6,10,5);d.castShadow=true;this.scene.add(d);this.ray=new THREE.Raycaster();this.ptr=new THREE.Vector2();addEventListener('resize',()=>this.resize());this.resize();this.loop();}
 resize(){const r=this.canvas.getBoundingClientRect();this.renderer.setSize(r.width,r.height,false);this.camera.aspect=Math.max(.5,r.width/Math.max(1,r.height));this.camera.updateProjectionMatrix();}
 clear(){while(this.root.children.length)this.root.remove(this.root.children[0]);this.tokens.clear();this.dice=null;}
 mat(c){return new THREE.MeshStandardMaterial({color:c,roughness:.58,metalness:.03});}
 sprite(text,size=.5){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d');x.font='150px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(text,128,136);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true}));s.scale.set(size,size,size);return s;}
 number(text,size=.48){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d');x.fillStyle='rgba(25,62,54,.30)';x.font='900 150px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(text,128,138);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthWrite:false}));s.scale.set(size,size,size);return s;}
 panda(color,variant){const g=new THREE.Group(),w=this.mat(0xffffff),b=this.mat(0x171717),a=this.mat(color);const head=new THREE.Mesh(new THREE.SphereGeometry(.38,20,16),w);head.scale.y=.92;g.add(head);[-.26,.26].forEach(x=>{const e=new THREE.Mesh(new THREE.SphereGeometry(.13,14,10),b);e.position.set(x,.25,0);g.add(e);});[-.14,.14].forEach(x=>{const e=new THREE.Mesh(new THREE.SphereGeometry(.075,12,8),b);e.position.set(x,.04,.33);e.scale.y=1.3;g.add(e);});const nose=new THREE.Mesh(new THREE.SphereGeometry(.05,10,7),b);nose.position.set(0,-.08,.35);g.add(nose);const scarf=new THREE.Mesh(new THREE.TorusGeometry(.27,.05,8,20),a);scarf.rotation.x=Math.PI/2;scarf.position.y=-.26;g.add(scarf);if(variant==='green'){const leaf=new THREE.Mesh(new THREE.ConeGeometry(.1,.34,6),a);leaf.position.set(.25,.48,.05);leaf.rotation.z=-.8;g.add(leaf);}if(variant==='purple'){[-.11,.11].forEach(x=>{const berry=new THREE.Mesh(new THREE.SphereGeometry(.07,10,8),a);berry.position.set(x,.49,.05);g.add(berry);});}if(variant==='orange'){const sun=new THREE.Mesh(new THREE.CylinderGeometry(.15,.18,.07,16),a);sun.rotation.x=Math.PI/2;sun.position.set(0,.47,.02);g.add(sun);}if(variant==='blue'){const mask=new THREE.Mesh(new THREE.BoxGeometry(.45,.09,.05),a);mask.position.set(0,.06,.35);g.add(mask);}return g;}
 diceMesh(){const mats=['⚀','⚁','⚂','⚃','⚄','⚅'].map(ch=>{const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,128,128);x.fillStyle='#111';x.font='88px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(ch,64,68);return new THREE.MeshStandardMaterial({map:new THREE.CanvasTexture(c)});});return new THREE.Mesh(new THREE.BoxGeometry(.78,.78,.78),mats);}
 build(game){this.clear();this.mode=game.mode;if(game.mode==='classic')this.buildClassic(game);else this.buildSnake(game);this.dice=this.diceMesh();this.dice.position.set(0,1.15,0);this.root.add(this.dice);this.sync(game);}
 buildClassic(){const tile=.66,off=4.62;this.camera.position.set(0,13,12.5);this.camera.lookAt(0,0,0);const base=new THREE.Mesh(new THREE.BoxGeometry(10.4,.35,10.4),this.mat(0xd6e8e2));base.position.y=-.26;this.root.add(base);for(let r=0;r<15;r++)for(let c=0;c<15;c++){let col=0xf8fbf9;if(r<6&&c<6)col=0xdff6ee;else if(r<6&&c>8)col=0xeee9ff;else if(r>8&&c<6)col=0xffefdc;else if(r>8&&c>8)col=0xe3edff;const m=new THREE.Mesh(new THREE.BoxGeometry(tile*.96,.16,tile*.96),this.mat(col));m.position.set(c*tile-off,0,r*tile-off);this.root.add(m);}CLASSIC_TRACK.forEach(([r,c],i)=>{let col=i%2?0xecf5f2:0xffffff;if(CLASSIC_CONFIG.safeCells.includes(i))col=0xfff0b4;const m=new THREE.Mesh(new THREE.BoxGeometry(tile*.92,.22,tile*.92),this.mat(col));m.position.set(c*tile-off,.12,r*tile-off);this.root.add(m);const n=this.number(String(i),.42);n.position.set(c*tile-off,.28,r*tile-off);this.root.add(n);if(CLASSIC_CONFIG.safeCells.includes(i)){const s=this.sprite('⭐',.28);s.position.set(c*tile-off,.38,r*tile-off);this.root.add(s);}const sp=this.classicSpecial(i);if(sp){const s=this.sprite(sp,.34);s.position.set(c*tile-off,.46,r*tile-off);this.root.add(s);}});const laneCols={green:0xcdf1d9,purple:0xe2dbff,orange:0xffdfbc,blue:0xd8e9ff},foods=['🥚','🥛','🐟','🥦','🍎','🥜'];for(const [color,lane] of Object.entries(HOME_LANES))lane.forEach(([r,c],i)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(tile*.92,.25,tile*.92),this.mat(laneCols[color]));m.position.set(c*tile-off,.14,r*tile-off);this.root.add(m);const s=this.sprite(foods[i],.34);s.position.set(c*tile-off,.42,r*tile-off);this.root.add(s);});const center=new THREE.Mesh(new THREE.CylinderGeometry(.72,.72,.3,4),this.mat(0xf5b63b));center.rotation.y=Math.PI/4;center.position.set(0,.15,0);this.root.add(center);const plate=this.sprite('🍽️',.58);plate.position.set(0,.58,0);this.root.add(plate);}
 classicSpecial(i){if(CLASSIC_SPECIALS.healthy[i])return CLASSIC_SPECIALS.healthy[i].icon;if(CLASSIC_SPECIALS.junk[i])return CLASSIC_SPECIALS.junk[i].icon;if(CLASSIC_SPECIALS.quiz.includes(i))return '❓';if(CLASSIC_SPECIALS.bonus[i])return CLASSIC_SPECIALS.bonus[i].icon;return null;}
 buildSnake(){this.camera.position.set(0,13.5,12.8);this.camera.lookAt(0,0,0);for(let n=1;n<=100;n++){const [r,c]=tileCoord(n),x=c*1.02-4.59,z=r*1.02-4.59;let col=n%2?0xeaf5f1:0xfafdfc;if(SNAKE_CONFIG.healthy[n])col=0xcdf2da;if(SNAKE_CONFIG.junk[n])col=0xf7d4d9;if(SNAKE_CONFIG.quiz.includes(n))col=0xd9e8ff;const m=new THREE.Mesh(new THREE.BoxGeometry(.94,.19,.94),this.mat(col));m.position.set(x,0,z);this.root.add(m);const num=this.number(String(n),.69);num.position.set(x,.24,z);this.root.add(num);const sp=SNAKE_CONFIG.healthy[n]?.icon||SNAKE_CONFIG.junk[n]?.icon||(SNAKE_CONFIG.quiz.includes(n)?'❓':SNAKE_CONFIG.power[n]?.icon);if(sp){const s=this.sprite(sp,.56);s.position.set(x,.48,z);this.root.add(s);}}this.addSnakes();this.addLadders();}
 snakePos(n){const [r,c]=tileCoord(n);return new THREE.Vector3(c*1.02-4.59,.35,r*1.02-4.59);}
 addSnakes(){for(const [a,b] of Object.entries(SNAKE_CONFIG.snakes)){const p1=this.snakePos(+a),p2=this.snakePos(+b),curve=new THREE.CatmullRomCurve3([p1,new THREE.Vector3((p1.x+p2.x)/2+1,.65,(p1.z+p2.z)/2),new THREE.Vector3((p1.x+p2.x)/2-1,.4,(p1.z+p2.z)/2+.6),p2]);this.root.add(new THREE.Mesh(new THREE.TubeGeometry(curve,36,.11,8,false),this.mat(0xe65568)));}}
 addLadders(){for(const [a,b] of Object.entries(SNAKE_CONFIG.ladders)){const p1=this.snakePos(+a),p2=this.snakePos(+b),dx=p2.x-p1.x,dz=p2.z-p1.z,len=Math.hypot(dx,dz),ang=Math.atan2(dz,dx);for(const side of [-.13,.13]){const rail=new THREE.Mesh(new THREE.BoxGeometry(len,.05,.05),this.mat(0x9b6633));rail.rotation.y=-ang;rail.position.set((p1.x+p2.x)/2+Math.sin(ang)*side,.36,(p1.z+p2.z)/2-Math.cos(ang)*side);this.root.add(rail);}for(let i=1;i<6;i++){const t=i/6,s=new THREE.Mesh(new THREE.BoxGeometry(.35,.05,.05),this.mat(0xc98945));s.rotation.y=-ang+Math.PI/2;s.position.set(p1.x+dx*t,.36,p1.z+dz*t);this.root.add(s);}}}
 sync(game){const palette={green:0x18b89c,purple:0x7657e8,orange:0xf28b34,blue:0x3d8de8},tile=.66,off=4.62;for(const pid of game.order){const p=game.players[pid];if(game.mode==='classic'){p.tokens.forEach((tok,i)=>{const key=`${pid}:${i}`;let g=this.tokens.get(key);if(!g){g=this.panda(palette[p.color],p.color);g.scale.setScalar(.72);this.tokens.set(key,g);this.root.add(g);}let pos;if(tok.state<0){const yards={green:[[-4,-4],[-3.25,-4],[-4,-3.25],[-3.25,-3.25]],purple:[[3.25,-4],[4,-4],[3.25,-3.25],[4,-3.25]],orange:[[3.25,3.25],[4,3.25],[3.25,4],[4,4]],blue:[[-4,3.25],[-3.25,3.25],[-4,4],[-3.25,4]]};const [x,z]=yards[p.color][i];pos=new THREE.Vector3(x,.62,z);}else if(tok.state<=50){const gi=globalCell(p.color,tok.state),[r,c]=CLASSIC_TRACK[gi];pos=new THREE.Vector3(c*tile-off,.62,r*tile-off);}else if(tok.state<=56){const [r,c]=HOME_LANES[p.color][tok.state-51];pos=new THREE.Vector3(c*tile-off,.62,r*tile-off);}else pos=new THREE.Vector3(0,.7,0);g.position.copy(pos);g.userData={pid,idx:i};});}else{const key=`${pid}:0`;let g=this.tokens.get(key);if(!g){g=this.panda(palette[p.color],p.color);this.tokens.set(key,g);this.root.add(g);}let pos;if(p.outside){const spots={green:[-5.4,-5.1],purple:[5.4,-5.1],orange:[5.4,5.1],blue:[-5.4,5.1]};const [x,z]=spots[p.color];pos=new THREE.Vector3(x,.7,z);}else pos=this.snakePos(p.position).setY(.7);g.position.copy(pos);g.userData={pid,idx:0};}}}
 tokenPos(pid,idx=0){return this.tokens.get(`${pid}:${idx}`)?.position.clone()||null;}
 highlight(items=[]){this.selectable=items;for(const [key,g] of this.tokens){const [pid,idx]=key.split(':');const on=items.some(x=>x.pid===pid&&String(x.idx)===idx);g.scale.setScalar((this.mode==='classic'?.72:1)*(on?1.18:1));g.traverse(o=>{if(o.material?.emissive)o.material.emissive.setHex(on?0x224400:0);});}}
 pick(x,y){const r=this.canvas.getBoundingClientRect();this.ptr.x=((x-r.left)/r.width)*2-1;this.ptr.y=-((y-r.top)/r.height)*2+1;this.ray.setFromCamera(this.ptr,this.camera);const objs=[];for(const g of this.tokens.values())g.traverse(o=>{if(o.isMesh)objs.push(o);});const h=this.ray.intersectObjects(objs);if(!h.length)return null;let o=h[0].object;while(o.parent&&!o.userData.pid)o=o.parent;return o.userData.pid?o.userData:null;}
 async animateFrom(pid,idx,start){const g=this.tokens.get(`${pid}:${idx}`);if(!g||!start)return;const end=g.position.clone(),st=performance.now(),dur=520;g.position.copy(start);return new Promise(res=>{const tick=now=>{const t=Math.min(1,(now-st)/dur),e=1-Math.pow(1-t,3);g.position.lerpVectors(start,end,e);g.position.y+=Math.sin(Math.PI*t)*.55;if(t<1)requestAnimationFrame(tick);else{g.position.copy(end);res();}};requestAnimationFrame(tick);});}
 async rollDice(v){if(!this.dice)return;const st=performance.now(),dur=850;return new Promise(res=>{const tick=now=>{const t=Math.min(1,(now-st)/dur),e=1-Math.pow(1-t,3);this.dice.rotation.x=e*Math.PI*(5+v*.1);this.dice.rotation.y=e*Math.PI*(7+v*.13);this.dice.position.set(Math.sin(t*Math.PI*2)*1.7,1.1+Math.sin(t*Math.PI)*2.8,Math.cos(t*Math.PI*2)*.9);if(t<1)requestAnimationFrame(tick);else{this.dice.position.set(0,1.15,0);res();}};requestAnimationFrame(tick);});}
 loop(){requestAnimationFrame(()=>this.loop());for(const g of this.tokens.values())g.rotation.y+=.003;this.renderer.render(this.scene,this.camera);}
}
