import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js";
import { classicPath } from "./game-logic.js";
import {FOOD_TILES,QUIZ_TILES} from "./data.js";

export class Game3D{
 constructor(canvas){
  this.canvas=canvas;this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});this.renderer.setPixelRatio(Math.min(2,devicePixelRatio||1));this.renderer.shadowMap.enabled=true;
  this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(42,1,.1,100);this.camera.position.set(0,12,12);this.camera.lookAt(0,0,0);
  this.root=new THREE.Group();this.scene.add(this.root);this.tokens=new Map();this.hitMeshes=[];this.dice=null;this.mode="snake";
  const hemi=new THREE.HemisphereLight(0xffffff,0x40605a,1.7);this.scene.add(hemi);const dir=new THREE.DirectionalLight(0xffffff,2.1);dir.position.set(5,10,4);dir.castShadow=true;this.scene.add(dir);
  const floor=new THREE.Mesh(new THREE.CylinderGeometry(8.5,8.5,.45,64),new THREE.MeshStandardMaterial({color:0xdcefe9,roughness:.8,metalness:.05}));floor.position.y=-.45;floor.receiveShadow=true;this.scene.add(floor);
  this.raycaster=new THREE.Raycaster();this.pointer=new THREE.Vector2();
  this.resize();addEventListener("resize",()=>this.resize());this.animate();
 }
 resize(){const r=this.canvas.getBoundingClientRect();this.renderer.setSize(r.width,r.height,false);this.camera.aspect=r.width/r.height;this.camera.updateProjectionMatrix()}
 clear(){while(this.root.children.length){const o=this.root.children.pop();o.traverse?.(x=>{x.geometry?.dispose?.();if(x.material){if(Array.isArray(x.material))x.material.forEach(m=>m.dispose?.());else x.material.dispose?.()}})}this.tokens.clear();this.hitMeshes=[];this.dice=null}
 makeTextSprite(txt,bg="#ffffff",fg="#102e29",scale=1){const c=document.createElement("canvas");c.width=256;c.height=256;const x=c.getContext("2d");x.fillStyle=bg;x.fillRect(0,0,256,256);x.font="120px sans-serif";x.textAlign="center";x.textBaseline="middle";x.fillStyle=fg;x.fillText(txt,128,137);const tex=new THREE.CanvasTexture(c);const mat=new THREE.SpriteMaterial({map:tex,transparent:true});const s=new THREE.Sprite(mat);s.scale.set(scale,scale,scale);return s}
 panda(color=0x0e8f79){const g=new THREE.Group();const white=new THREE.MeshStandardMaterial({color:0xffffff,roughness:.55});const dark=new THREE.MeshStandardMaterial({color:0x171717,roughness:.65});const acc=new THREE.MeshStandardMaterial({color,roughness:.45,metalness:.08});const head=new THREE.Mesh(new THREE.SphereGeometry(.38,24,20),white);head.scale.y=.9;head.castShadow=true;g.add(head);for(const x of [-.25,.25]){const e=new THREE.Mesh(new THREE.SphereGeometry(.14,16,12),dark);e.position.set(x,.25,0);g.add(e)}for(const x of [-.15,.15]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.075,12,8),dark);eye.position.set(x,.06,.33);eye.scale.y=1.4;g.add(eye)}const nose=new THREE.Mesh(new THREE.SphereGeometry(.055,12,8),dark);nose.position.set(0,-.07,.36);g.add(nose);const collar=new THREE.Mesh(new THREE.TorusGeometry(.28,.055,10,24),acc);collar.rotation.x=Math.PI/2;collar.position.y=-.25;g.add(collar);g.userData.baseY=0;return g}
 buildSnake(game){
  this.clear();this.mode="snake";const size=1.08,off=4.86;
  for(let n=1;n<=100;n++){const row=Math.floor((n-1)/10),colIn=(n-1)%10,col=row%2?9-colIn:colIn;const x=colIn*size-off,z=row*size-off;let color=(n%2?0xe8f6f1:0xd8eee6);if(FOOD_TILES[n])color=FOOD_TILES[n].kind==="good"?0xbceccf:0xf4c1c6;if(QUIZ_TILES.includes(n))color=0xbfdcff;const m=new THREE.Mesh(new THREE.BoxGeometry(1,.18,1),new THREE.MeshStandardMaterial({color,roughness:.55,metalness:.04}));m.position.set(x,0,z);m.receiveShadow=true;m.userData={tile:n};this.root.add(m);const label=this.makeTextSprite(String(n), "#ffffff","#24443d",.35);label.position.set(x,.18,z+.34);this.root.add(label);if(FOOD_TILES[n]){const food=this.makeTextSprite(FOOD_TILES[n].icon,"rgba(0,0,0,0)","#fff",.72);food.position.set(x,.4,z);this.root.add(food)}else if(QUIZ_TILES.includes(n)){const q=this.makeTextSprite("❓","rgba(0,0,0,0)","#fff",.65);q.position.set(x,.38,z);this.root.add(q)}}
  this.addDice();this.sync(game);
 }
 buildClassic(game){
  this.clear();this.mode="classic";const tile=.68,off=4.76;for(let r=0;r<15;r++)for(let c=0;c<15;c++){let color=0xf3f7f5;const home=(r<6&&c<6)||(r<6&&c>8)||(r>8&&c<6)||(r>8&&c>8);if(home)color=0xddeae5;const m=new THREE.Mesh(new THREE.BoxGeometry(tile,.17,tile),new THREE.MeshStandardMaterial({color,roughness:.65}));m.position.set(c*tile-off,0,r*tile-off);m.receiveShadow=true;this.root.add(m)}
  const path=classicPath();path.forEach((p,i)=>{const [r,c]=p;const x=c*tile-off,z=r*tile-off;const plate=new THREE.Mesh(new THREE.BoxGeometry(tile*.94,.25,tile*.94),new THREE.MeshStandardMaterial({color:i%2?0xe8f5f1:0xffffff,roughness:.45}));plate.position.set(x,.12,z);this.root.add(plate);const cellNum=i+1;if(FOOD_TILES[cellNum]){const s=this.makeTextSprite(FOOD_TILES[cellNum].icon,"rgba(0,0,0,0)","#fff",.48);s.position.set(x,.38,z);this.root.add(s)}else if(QUIZ_TILES.includes(cellNum)){const s=this.makeTextSprite("❓","rgba(0,0,0,0)","#fff",.44);s.position.set(x,.38,z);this.root.add(s)}})
  const colors=[0x13b886,0x7b61ff,0xff9f1c,0x2f7de1];[[2,2],[2,12],[12,2],[12,12]].forEach((rc,i)=>{const [r,c]=rc;const ring=new THREE.Mesh(new THREE.CylinderGeometry(1.25,1.25,.12,40),new THREE.MeshStandardMaterial({color:colors[i],transparent:true,opacity:.25}));ring.position.set(c*tile-off,.08,r*tile-off);this.root.add(ring)})
  this.addDice();this.sync(game);
 }
 addDice(){const mats=[1,2,3,4,5,6].map(n=>{const c=document.createElement("canvas");c.width=128;c.height=128;const x=c.getContext("2d");x.fillStyle="#fff";x.fillRect(0,0,128,128);x.fillStyle="#111";x.font="88px sans-serif";x.textAlign="center";x.textBaseline="middle";x.fillText(["⚀","⚁","⚂","⚃","⚄","⚅"][n-1],64,69);return new THREE.MeshStandardMaterial({map:new THREE.CanvasTexture(c),roughness:.35})});this.dice=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),mats);this.dice.position.set(0,4,0);this.dice.castShadow=true;this.root.add(this.dice)}
 tokenKey(uid,idx=0){return `${uid}:${idx}`}
 sync(game){if(!game)return;const colors=[0x13b886,0x7b61ff,0xff9f1c,0x2f7de1];for(const uid of game.order){const p=game.players[uid];if(this.mode==="snake"){const key=this.tokenKey(uid,0);let t=this.tokens.get(key);if(!t){t=this.panda(colors[p.slot-1]);this.tokens.set(key,t);this.root.add(t);this.hitMeshes.push(t)}const pos=p.snake.inYard?0:p.snake.pos;let x,z;if(pos===0){const yards=[[-5.7,-5.5],[5.7,-5.5],[-5.7,5.5],[5.7,5.5]];[x,z]=yards[p.slot-1]}else{const row=Math.floor((pos-1)/10),ci=(pos-1)%10,col=row%2?9-ci:ci;x=col*1.08-4.86;z=row*1.08-4.86}t.position.set(x,.75,z);t.userData={uid,idx:0}}
    else{p.classic.tokens.forEach((tok,i)=>{const key=this.tokenKey(uid,i);let t=this.tokens.get(key);if(!t){t=this.panda(colors[p.slot-1]);t.scale.set(.78,.78,.78);this.tokens.set(key,t);this.root.add(t);this.hitMeshes.push(t)}let x,z;if(tok.p<0){const yardSets=[[[-4.2,-4.2],[-3.3,-4.2],[-4.2,-3.3],[-3.3,-3.3]],[[3.3,-4.2],[4.2,-4.2],[3.3,-3.3],[4.2,-3.3]],[[-4.2,3.3],[-3.3,3.3],[-4.2,4.2],[-3.3,4.2]],[[3.3,3.3],[4.2,3.3],[3.3,4.2],[4.2,4.2]]];[x,z]=yardSets[p.slot-1][i]}else{const cell=this.classicCell(p,tok);x=cell[1]*.68-4.76;z=cell[0]*.68-4.76}t.position.set(x,.68,z);t.userData={uid,idx:i}})}
  }}
 classicCell(p,tok){const START=[0,20,40,60],path=classicPath();if(tok.p<52)return path[(START[p.slot-1]+tok.p)%52];const lane=tok.p-52,lanes=[[[7,13],[7,12],[7,11],[7,10],[7,9]],[[1,7],[2,7],[3,7],[4,7],[5,7]],[[7,1],[7,2],[7,3],[7,4],[7,5]],[[13,7],[12,7],[11,7],[10,7],[9,7]]];return lanes[p.slot-1][Math.min(4,lane)]}
 async rollDice(v){if(!this.dice)return;const start=performance.now(),dur=950,base=this.dice.position.clone();return new Promise(res=>{const tick=(now)=>{const t=Math.min(1,(now-start)/dur),ease=1-Math.pow(1-t,3);this.dice.rotation.x=ease*Math.PI*6+v*.2;this.dice.rotation.y=ease*Math.PI*8+v*.3;this.dice.position.y=1.1+Math.sin(t*Math.PI)*3.3;this.dice.position.x=Math.sin(t*Math.PI*2)*2.1;this.dice.position.z=Math.cos(t*Math.PI*2)*1.3;if(t<1)requestAnimationFrame(tick);else{this.dice.position.set(0,1.15,0);res()}};requestAnimationFrame(tick)})}
 pickToken(clientX,clientY){const r=this.canvas.getBoundingClientRect();this.pointer.x=((clientX-r.left)/r.width)*2-1;this.pointer.y=-((clientY-r.top)/r.height)*2+1;this.raycaster.setFromCamera(this.pointer,this.camera);const objs=[];for(const g of this.tokens.values())g.traverse(o=>{if(o.isMesh)objs.push(o)});const hits=this.raycaster.intersectObjects(objs,false);if(!hits.length)return null;let o=hits[0].object;while(o.parent&&!o.userData.uid)o=o.parent;return o.userData.uid?o.userData:null}
 highlight(selectable){for(const [key,g] of this.tokens){const [uid,idx]=key.split(":");const on=selectable.some(s=>s.uid===uid&&String(s.idx)===idx);g.scale.setScalar(on?1.12:(this.mode==="classic"?.78:1));g.traverse(o=>{if(o.material&&o.material.emissive)o.material.emissive.setHex(on?0x334400:0x000000)})}}
 animate(){requestAnimationFrame(()=>this.animate());for(const [k,g] of this.tokens){g.rotation.y+=.005;g.position.y+=(Math.sin(performance.now()/500+g.position.x)-Math.sin((performance.now()-16)/500+g.position.x))*.018}this.renderer.render(this.scene,this.camera)}
}